### ISSUE TITLE
websocket fails to initialize

### ISSUE THREAD

**Issue by kamal** [ariya/phantomjs#10071]
_**[kamal.fa...@gmail.com](http://code.google.com/u/106502573808759789607/) commented:**_
> I'm experimenting phantom.js with Socket.IO. The preferred transport for WebKit-based browsers is using the websocket transport. However, when I try this with Phantom.js 1.1.0, I get this error message
> 
> QMetaObject::invokeMethod: No such method WebCore::SocketStreamHandlePrivate::socketSentData()
> 
> This seems to be the same problem described on http://bugreports.qt.nokia.com/browse/QTWEBKIT-302

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #71](http://code.google.com/p/phantomjs/issues/detail?id=71).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This bug was reported against PhantomJS 1.x, which is no longer being developed.  Version 2.0 includes a major update to Qt and Webkit, which may well have fixed this problem (the upstream bug report you linked to is inconclusive, but code inspection leads me to believe it has been fixed).  Unfortunately, your bug report does not contain enough information for us to test it ourselves.  Would you mind downloading the current version from http://phantomjs.org/download.html and telling us whether it does work?

Because there are many old bugs which we believe to have been fixed in 2.0 but do not have enough information for us to test them, this bug will be closed in one month if we don't hear back from you.

**Comment by frankiek3** [comment]
This was fixed a long time ago in webkit...
Reference: https://bugs.webkit.org/show_bug.cgi?id=47284
Revision : 69221
Timestamp: 10/06/10 12:16:02 (5 years ago)
