### ISSUE TITLE
problems rendering SVG

### ISSUE THREAD

**Issue by bobmonteverde** [ariya/phantomjs#10098]
_**[b...@montev.com](http://code.google.com/u/114574023430741577808/) commented:**_
> <b>What steps will reproduce the problem?</b>
1. phantomjs examples/rasterize.js http://www.krunc.com/phantomjs/test.html test.png
> 2. look at horrific output of svg
> 3. (test svg output in browser or any other SVG viewer which displays it accurately)
> 
> <b>What is the expected output? What do you see instead?</b>
Expected: a nice line graph with 4 lines on it.
> Actual: jumbled text of the axis labels and legend labels
> 
> <b>What version of the product are you using? On what operating system?</b>
Current version from the git repo, on Ubuntu 10.10
> 
> <b>Please provide any additional information below.</b>

> I can't pinpoint the cause, obviously some SVG renders correctly.  It appears that maybe after a certain number of elements in the SVG things get screwed up, but have not confirmed any specific cause.
> 
> I will research further if I can get details on how SVG is rendered.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #98](http://code.google.com/p/phantomjs/issues/detail?id=98).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
@bobmonteverde This bug was reported against PhantomJS 1.x, which is no longer being developed. Version 2.0 includes a major update to Qt and Webkit, which may well have fixed this problem. Unfortunately, the test case you originally posted appears to have been taken down.  Would it be possible for you to test version 2.0 (http://phantomjs.org/download.html) and/or attach a current test case to this bug?

Because this bug is very old, the test case is no longer available, and, if there's still a bug it's almost certainly a Webkit problem rather than a problem with PhantomJS itself, we will close this issue in one month if we haven't heard from you.

@bharathy That sounds like an unrelated problem, please file a new bug.

**Comment by ariya** [comment]
We will close this one due to lack of response and we can't follow it up without it.
