### ISSUE TITLE
Ability to access file: URI

### ISSUE THREAD

**Issue by morganrallen** [ariya/phantomjs#10231]
_**[morganrallen@gmail.com](http://code.google.com/u/morganrallen@gmail.com/) commented:**_

> Currently only local to remote file access is supported. But when loading html from data:text/html, or file:///Some/local/file.html relative paths are not honored. Or in the case the script sources have are absolute with file:/// there is an error thrown.
> 
> Not allowed to load local resource:

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #231](http://code.google.com/p/phantomjs/issues/detail?id=231).
:star2: &nbsp; **18** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
It's not 100% clear to me what this feature request is asking for: is it

[] relative URLs should work correctly when the base URL is `file:`-schema (this strikes me as a bug if it doesn't already work)
[] PhantomJS should honor a resource request for a `file:` URL from a page loaded from an `http:` URL (this strikes me as something we don't want to do, because "normal" browsers deliberately don't do it)
[] The PhantomJS controller script should be able to *force* a page loaded from an `http:` URL to pull a resource from a `file:` URL (this is a legit feature request)
[] any or all of the above with `data:` for the base document (relative URLs don't make sense for `data:` but the other two are as for `http:`

?

**Comment by stevenvachon** [comment]
I'm pretty sure that it's the same as #10291

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
