### ISSUE TITLE
Canvas toDataURL encode is different

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10455]
_**[d...@omniscience.co.il](http://code.google.com/u/114697271554048383780/) commented:**_

> Which version of PhantomJS are you using? 1.5
> 
> <b>What steps will reproduce the problem?</b>
> 1. I created a simple html page with a 200x200 canvas elemnt
> 2. In console: document.getElementById('canvas').toDataURL();
> 3. In PhantomJS I opend a page to the html file then after the page loaded I run an evaluate function to get the toDataURL data
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> See Files attached
> 
> Which operating system are you using? Ubuntu 11.04
> 
> Did you use binary PhantomJS or did you compile it from source? Latest binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #455](http://code.google.com/p/phantomjs/issues/detail?id=455).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by vivin** [comment]
I'm able to get a png of proper size if I use `toDataURL` with an explicit quality-argument:

```javascript
var base64 = canvas.toDataURL("image/png", 0);
```

It's when I don't provide an explicit quality-argument, that I end up with a very large png. I traced the problem to [`JSHTMLCanvasElement::toDataURL`](https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebCore/bindings/js/JSHTMLCanvasElementCustom.cpp#L123).

There, we have the following few lines of code:

```cpp
double quality;
double* qualityPtr = 0;
if (exec->argumentCount() > 1) {
    JSValue v = exec->argument(1);
    if (v.isNumber()) {
        quality = v.toNumber(exec);
        qualityPtr = &quality;
    }
}
```

If an explicit quality-argument is not provided, `qualityPtr` remains `null`. Later, this pointer is passed to  [`encodeImage`](https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebCore/platform/graphics/qt/ImageBufferQt.cpp#L259) in `ImageBufferQt.cpp`. There, we have the following lines:

```cpp
int compressionQuality = 100;
if (quality && *quality >= 0.0 && *quality <= 1.0)
    compressionQuality = static_cast<int>(*quality * 100 + 0.5);
```

Since `quality` (which is `qualityPtr`) is not a valid pointer, the `if` clause never gets executed, and you end up with `compressionQuality` set to `100`. When the image is finally saved to the buffer using [`QPixmap::save`](http://doc.qt.io/qt-5/qpixmap.html#save-2), you end up with a large, uncompressed file; from the documentation:

> The quality factor must be in the range [0,100] or -1. Specify 0 to obtain small compressed files, 100 for large uncompressed files, and -1 to use the default settings.

According to the HTML5 spec, [§4.12.4.4](https://html.spec.whatwg.org/multipage/scripting.html#serialising-bitmaps-to-a-file) says that the quality argument only applies to images of type `image/jpeg`. It makes sense to default to 100 (although I think Firefox and Chrome use 92) in the case of JPEG, because you still want to render the image with decent quality. But in phantomjs, this number ends up affects the level of *compression* that is performed for PNGs. The compression doesn't affect the quality of the image, since PNG is lossless; it only ends up affecting the size. So a quality of 100 results in a PNG image without any compression, and 0 results in a PNG image with maximum compression.

I think `encodeImage` should take the image type into account before setting the quality value. It should only honor that argument if the type is JPEG; otherwise it should use `-1`, so that  `QPixmap::save` uses the default settings for that type. 

I can get started on a pull-request for this.

**Comment by prasanthsd** [comment]
Is this going to be fixed?

**Comment by vivin** [comment]
The fix is upstream in Qt-webkit.

**Comment by Vitallium** [comment]
Yup. Closing. Thank you @vivin !
