### ISSUE TITLE
PDF document has additional empty page at the end

### ISSUE THREAD

**Issue by wawanawna** [ariya/phantomjs#10582]
_**[vladimir...@sematext.com](http://code.google.com/u/116154130902633268580/) commented:**_

> Thanks for this nice tool at first.
> 
> I have small problem with rendering pdf file: sometimes pdf file has an extra page at the end and this page is empty.
> 
> It will be great if I could avoid this page.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #582](http://code.google.com/p/phantomjs/issues/detail?id=582).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by agairing** [comment]
`overflow:hidden` did the trick.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://panbostone.com/sufficient.php?l2g>

 

klaus@hebsgaard.dk

**Comment by ebdrup** [comment]
Adding `overflow:hidden` to all my container elements, and adding normalize.css did not fix the bug for me. I discovered that the root `html`-element in the HTML DOM was causing the issue, probably because I was compensating for the phantom 2.1 pdf scaling bug https://github.com/ariya/phantomjs/issues/12685

The fix for this was adding this code:
```js
var $html = $(document.getElementsByTagName('html')[0]);
$html.height(0);
```
(I'm using jQuery, because we already have it on the page, there should be an easy Vanilla JS solution too)

**Comment by Llorx** [comment]
Mixing jQuery and default Javascript is never a good idea.

As webpages only have one `html` element, you can do:

    $("html").height(0);

And if you really want to apply it to the first element, you can do:

    $("html").first().height(0);

I feel a bit Stack Overflow right now... xD

**Comment by Quovandius** [comment]
Tips of @Llorx works for me ;) thx for this

**Comment by gletsch** [comment]
Also had this problem after scaling down a table, the provided fix by ebdrup worked like a charm :1st_place_medal: . Thanks a lot, i was already ripping my hair out because of that :)
PS.: jQuery isnt needed at all for his fix, it also works in an css tag
