### ISSUE TITLE
Phantomjs does not exit if file has Parse Errors

### ISSUE THREAD

**Issue by ahawkins** [ariya/phantomjs#10687]
_**[m...@broadcastingadam.com](http://code.google.com/u/116377228668850173159/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. Create a file with only this line: thisIsUndefined!. Save the file as &quot;foo.js&quot;
> 2. $ phantomjs foo.js
> <b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> adam at mba : ~ % phantomjs foo.js
> SyntaxError: Parse error
> .....
> 
> phantomjs just hangs. The process should exit(1) if there is a syntax error in the executing file.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #687](http://code.google.com/p/phantomjs/issues/detail?id=687).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by cyphunk** [comment]
how I get around this. When script hangs, execute with nodejs to see if syntax error is at fault.

**Comment by graceful-code** [comment]
If page.onError or window.onerror could listen for these syntax and runtime errors, then at least we could catch the errors and let Phantom move on instead of just hanging. I believe this is related to #10537

**Comment by GDmac** [comment]
I bumped into this with the rasterize.js example script linked from the screen capture page
http://phantomjs.org/screen-capture.html

Testing from terminal outputs following message and does not exit (need ctrl-c)
``ReferenceError: Strict mode forbids implicit creation of global property 'pageWidth'
phantomjs://code/rasterize.js:23 in global code
``

I found another tip on stackoverflow to wrap the script in a try-catch block,
http://stackoverflow.com/questions/11180662/automatically-close-phantomjs-after-running-script

It would sure be nice to have an option to have PhantomJS just exit on parse error...

PhantomJS 2.1.1 (macosx)

**Comment by szakharchenko** [comment]
@acidus99:
> It's pretty ridiculous that this bug still exists.

It's 2016 and I couldn't agree more.

**Comment by cyphunk** [comment]
@szakharchenko @acidus99 

Thats true. Also though it's free software so there is that

**Comment by ariya** [comment]
> It's pretty ridiculous that this bug still exists.
> It's 2016 and I couldn't agree more.

None of us got paid to work on this. So the bug may still continue to exist for the next 25 years if nobody steps up and offers a fix.

**Comment by GDmac** [comment]
@ariya it is just a bug-report that parse errors stop execution but don't exit the program.
This is either intentional (memory debugging?, mem-page dumps?) or needs label 'bug'.
Yes, there are ways to circumvent this (JShint, validate your scripts before running),
Still it seems somewhat silly to keep the process running when nothing goes, 
or, again, am i missing something?

**Comment by bronson** [comment]
No, it's not intentional.  It's just a hard problem to fix.

At this point you could write the fix yourself, pay someone to fix it, or keep living with it.  Going over earlier comments isn't likely to help.

**Comment by ariya** [comment]
@GDmac I wish it was that easy. There is a complication in the way PhantomJS uses the API of (Qt)WebKit to run a script. If you think about it, the browser doesn't exit if any scripts in the page is invalid. Since (Qt)WebKit is obviously designed with that use case in mind, it is not easy to discover that the main script has an early error and thus it has to be terminated.

I could go on and explain the problem in depth, but I hope you get the point. It's not a 5-minute fix, it requires a careful thought and consideration. And since there is a huge increasing demand for other features and fixes for PhantomJS (while the amount of volunteering work remains the same), this creates a situation where there are competing priorities.

**Comment by GDmac** [comment]
Thanks @bronson and @ariya for the explanations and clearing up things.

**Comment by szakharchenko** [comment]
I really don't know if a solution to such a venerable issue can really be that obvious, but it fixes my immediate problem.

**Comment by Vitallium** [comment]
Duplicated. Please see #12973

**Comment by GDmac** [comment]
Duplicate? 12973 is about hang on trying to open non-existing files and callbacks not being called.
This issue is about hang on parse errors in main script. Sorry to see this closed.

**Comment by Vitallium** [comment]
@GDmac sorry, its title is misleading but these issues are about the same problem. I'll change the title.
