### ISSUE TITLE
renderBase64('GIF') returns empty string

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10888]
_**[bobmy...@gmail.com](http://code.google.com/u/101119179606492669864/) commented:**_
> Running binary version of Phantom JS 1.7.0 under W8.
> 
> page.renderBase64('GIF') returns an empty string, although the same code works perfectly with either 'PNG' or 'JPG'.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #888](http://code.google.com/p/phantomjs/issues/detail?id=888).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by radiosilence** [comment]
Ok so it's only been a few years.

**Comment by radiosilence** [comment]
Right, on investigation.

QImageWriter doesn't actually support PDF (at all), or GIF (writing).

PDF working for render() is explained in that `WebPage::render` has a special if case if the format is pdf/filename is pdf. This calls `WebPage::renderPdf` which does it's own thing.

This if statement is not reflected in renderBase64 and thus, because PDF/GIF are not in `QImageWriter::supportedImageFormats()`:

https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L987

It returns an empty string, which is really bad as it should really throw some sort of error here.

I'd suggest that we adapt `WebPage::renderPdf` for use in renderBase64 (in fact, I'm not sure why there isn't more code-reuse between `WebPage::render` and `WebPage::renderBase64` - it seems more like an after-though), and add in a gif library (from what I've read there's a GIF plugin that's disabled by default in QT-4.8?) and add that them to the default build process.

Unfortunately I'm not super knowledgeable about building C++ stuff so unless someone could guide me in the right direction I can't do a PR or anything.

**Comment by Vitallium** [comment]
As of 2.0 we don't support rendering to GIF anymore.

**Comment by wangmerry** [comment]
PNG
