### ISSUE TITLE
PhantomJS should support a defined screen size for css media queries

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10895]
_**[david.bu...@edoceo.com](http://code.google.com/u/100813199769666372911/) commented:**_

> Which version of PhantomJS are you using?
> Using 1.7 binary
> 
> <b>What steps will reproduce the problem?</b>
> 1. Set Viewport size
> 2. Load Page
> 3. Page is still wider than screen, CSS rules not followed.
> 
> <b>What is the expected output? What do you see instead?</b>
> I wanted the rendered PNG to more closely resemble what is seen on mobile or tablets.
> 
> <b>Which operating system are you using?</b>
> Gentoo 64bit
> 
> <b>Please provide any additional information below.</b>
> 
> It seems that rules from the responsive CSS methods are not respected.
> 
> I had some rules that said resize elements based on screen.  I've tried to override the screen object in the page too but that didn't work either.
> 
> I'll post my script and some PNG images shortly

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #895](http://code.google.com/p/phantomjs/issues/detail?id=895).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by rbolton240** [comment]
This sounds like the problem I am experiencing... 

I am trying to screen capture a web page (www.constructionequipment.com) using PhantomJSDriver, which works fine locally on my development box but when ran from a web server (without a display) does not properly handle detection of the screen due to the responsive nature of the web page.

What I am seeing happen (on the server) is the horizontal navigation bar at the top of the page always appears to display in a mobile mode (for responsive design) when screen captured, this is regardless of any width that I force the browser window to.

What I am seeing happen (on my development box) is the responsive menu adjusts appropriately as I resize the window programmatically. No issue here.

I was looking at the CSS for www.constructionequipment.com and found a media query being used ("@media" screen) which provides conditional logic for which CSS block to use based on the screen size.

I am thinking that the PhantomJS Driver is (in the case of running on the server) not properly detecting the screen width (since there is no display).

It should be noted that other responsive websites like CNN.com for example, work fine.

Has anyone else encountered this issue?

Thanks in advance.

Below is an attached screen capture of a dropdown menu in a wide browser window (which should be using a navigation bar instead). This was captured by my application running in a server environment and illustrates the problem I am seeing. My application works fine when ran locally.

![wide with mobile menu](https://cloud.githubusercontent.com/assets/6028190/6805220/39673a40-d218-11e4-93f5-50a4fc570f01.Jpeg)

You can go to constructionequipment.com and horizontally resize the window to see how it should behave.

wide with mobile menu

Custom .NET/C# application using...

Selenium WebDriver API .NET Bindings
Runtime Version v4.0.30319
Version 2.44.0.0

phantomjs.exe

Development machine: Windows 7

Server machine: Win Server 2008 R2

.NET version v4.0.30319

Information about CSS @Media queries
http://stackoverflow.com/questions/4189868/what-does-media-screen-and-max-width-1024px-mean-in-css

**Comment by jayesh22c** [comment]
Hello Aria,

I am using phamtomJSDriver in java to capture screen of the given URL my problem is that it is capturing the full page in case of one page site the size of image goes to 10-12 MBs . Is there any way to capture only visible portion of the page ? I am using GhostDriver.

Thanks

**Comment by gmisura** [comment]
From: http://phantomjs.org/screen-capture.html

var page = require('webpage').create();
//viewportSize being the actual size of the headless browser
page.viewportSize = { width: 1024, height: 768 };

Adjust to your needs.

**Comment by jayesh22c** [comment]
gmisura : I am not talking about the ViewPort size I am talking about the size of the image captured.
Like if the viewPort is set to (1024x768) then width of image will be same as viewport's width i.e.768 but its height will be of full page. I want the height of image also 1024.

**Comment by iradul** [comment]
To render only view-port you should adjust [```clipRect```](http://phantomjs.org/api/webpage/property/clip-rect.html), so something like this :
```javascript
var vps = page.viewportSize,
    clipRect = {
        top: 0,
        left: 0,
        height: vps.height,
        width: vps.width
    },
    previousClipRect = page.clipRect;

page.clipRect = clipRect;
page.render(targetFile);
page.clipRect = previousClipRect;
```

**Comment by jayesh22c** [comment]
@iradul  here is my java code :                     
WebDriver driver = new PhantomJSDriver(desiredCapabilities);
                    driver.manage().window().setSize(new Dimension(1024,768));
		    driver.get(url);
		    driver = new Augmenter().augment(driver);
		    File srcFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		    FileUtils.copyFile(srcFile, new File("screenShot/"+name+".png"));
		    System.out.println("*****************Captured Screen**********************");
		    driver.quit();
for JS your code works fine :+1:  and thanks for that but I am looking for something like that in java.
thanks

**Comment by iradul** [comment]
@jayesh22c, I never used GhostDriver before but if you could somehow execute javascript code using WebDriver that might solve your problem. Take a look at [this](https://github.com/detro/phantomjsdriver-examples/blob/master/src/test/java/examples/Canvas.java) example, though this will probably execute javascript in page context.

**Comment by jayesh22c** [comment]
@iradul  thanks :+1:
