### ISSUE TITLE
set window.devicePixelRatio for 'retina' screenshots

### ISSUE THREAD

**Issue by cjroebuck** [ariya/phantomjs#10964]
_**[toph...@gmail.com](http://code.google.com/u/106253888473198258953/) commented:**_

> Is is possible to set or emulate window.devicePixelRatio=2 for rendering retina screenshots. I want to emulate a retina iphone and take a screenshot, I've tried scaling the page by 2, and doubling the viewport but this isnt the same.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #964](http://code.google.com/p/phantomjs/issues/detail?id=964).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ashkulz** [comment]
@vegetableman: I'd recommend you try to upstream this at codereview.qt-project.org as the fix looks very simple.

**Comment by vegetableman** [comment]
@ashkulz sure but is that a public repo? I don't see any git url to clone.

**Comment by ashkulz** [comment]
Uhm, I'd recommend that you read [Contributing to Qt](https://www.qtdeveloperdays.com/sites/default/files/contributing%20qt.pdf) and [Introduction to Gerrit](http://qt-project.org/wiki/Gerrit-Introduction) and try to get your change accepted in the `dev` branch of `qt/qtwebkit`.

**Comment by vegetableman** [comment]
Thanks @ashkulz for the links. Will try to send a PR sometime this week.

**Comment by Aeon** [comment]
Will this be in 2.0?

**Comment by ashkulz** [comment]
Since `2.0` has been released, nope :frowning:

**Comment by pholmstr** [comment]
Any interest in getting this feature implemented?

**Comment by Bellardia** [comment]
@vegetableman Hey, any way you could quickly list build instructions for those of us who need this now?

**Comment by tiesselune** [comment]
+1 @Bellardia @vegetableman It would indeed be helpful for some of us.

**Comment by vegetableman** [comment]
The build instructions are the same as mentioned on the phantomjs docs. http://phantomjs.org/build.html
The changes are really minute.

**Comment by tiesselune** [comment]
Thank you for the feedback then ;)

**Comment by tiesselune** [comment]
Ok, I got it built and everything works fine. Except one thing though : I intended to use the `page.render` function; but it seems @vegetableman's fix does not influence the rendering. (ex: media queries don't get called properly) There might be something to do there...

**Comment by vegetableman** [comment]
@tiesselune did you try the code at https://github.com/ariya/phantomjs/issues/10964#issuecomment-67550290?

**Comment by tiesselune** [comment]
Yes, I pretty much did ^^. The problem lies elswhere : after my tests, when rendering, the image was always the viewport's size with an obvious pixel ratio of 1... I've looked at the code, and I believe we should change some of QtWebkit rendering functions for it to work... ?


My media-queries are of this kind :

    @media screen and (min-width : 567px) and (min-height : 340px)

But using a pixel ratio of 2, the minimum real width of the viewport to enter the media query should be `1134px` but it does not enter it, neither does it double the size of the on-screen html elements like it would on a real-world device...

Anyway, I've found another solution by applying a `scale` transform on the body element, and pre-compute the media-queries in the `<style>` tags with a regex to change its values according to the desired pixel ratio *before* it takes the screencap. I was not able to do it another way. :/

**Comment by vegetableman** [comment]
@tiesselune you are right, now that I remember it, the code (more of a hack) only handles setting the device pixel ratio to the desired value, with no effects on rendering of the page whatsoever. It only allows getting past the css media queries using ```-webkit-min-device-pixel-ratio```. So, the feature is still very much incomplete :(.

**Comment by doriandrn** [comment]
Hey guys,

Is the bounty on this still alive? :)

**Comment by pholmstr** [comment]
I will still honor bounty if someone can get this in phantomjs

**Comment by Paxa** [comment]
Would be nice to have this feature

**Comment by wxqqh** [comment]
I try this `page.devicePixelRatio = 2;`, but seen that it is not work with media queries

**Comment by erm3nda** [comment]
Im sorry to ask this.. but.. is not good enough the "solution" posted by @tiesselune?
It's a bit hard to understand the current stage of this problem.

As I undestand, you got a solution, but wanna get it coded in the PhantomJS itself instead of hack the js file, right?

**Comment by DeviaVir** [comment]
@erm3nda don't mean to sound like an asshole but he's basically suggesting what
I wrote a year ago, which is also in this comment thread:
https://github.com/ariya/phantomjs/issues/10964#issuecomment-67542804

Just wanted to point that out.




On Wed, Jan 20, 2016 at 7:55 PM, M3nda < notifications@github.com [notifications@github.com] > wrote:
Im sorry to ask this.. but.. is not good enough the "solution" posted by @tiesselune [https://github.com/tiesselune] ?
It's a bit hard to understand the current stage of this problem.

As I undestand, you got a solution, but wanna get it coded in the PhantomJS
itself instead of hack the js file, right?

—
Reply to this email directly or view it on GitHub
[https://github.com/ariya/phantomjs/issues/10964#issuecomment-173443942] .[https://github.com/notifications/beacon/AAveXwBsTYWfNOsCq3jR3rM8bIKKNwJjks5pcE4ngaJpZM4Ai5Aw.gif]

**Comment by erm3nda** [comment]
Don't meant to be dumb, but maybe you can compile a PhantomJS with your js file builtin and accepting a new parameter --retina=x so if you pass that, PhantomJS would chain internally the file.
As i understand they only want a capable "PhantomJS", meaning no using external file. If you put it inside is not external anymore and you can claim that bounty.

I've never tried to do that, but never is late to try out.

**Comment by DeviaVir** [comment]
@erm3nda that's the first thing I tried, but since this needs to be fixed upstream first, and I don't know enough about Qt, I threw together this working hack.

See this other comment, also in this thread, who also pointed this out: https://github.com/ariya/phantomjs/issues/10964#issuecomment-70423243

**Comment by erm3nda** [comment]
Just to clarify.

If I build a binary of PhantomJS 2.0 wich applies your code by a parameter would be enough for the bounty? I'll spent my day looking the PhantomJS source and guessing for a way to hack it.

**Comment by erm3nda** [comment]
Doh, you were right at "but since this needs to be fixed upstream first". Seems is the Qt:WebPage which has to do the main work, but also needed to add the params on the render. I'll read more untill talk more about it :+1:

**Comment by pholmstr** [comment]
https://github.com/DeviaVir/pixelratio-screenshots seems like most deserving of bounty, but I really wanted this in phantomjs proper :(

**Comment by DeviaVir** [comment]
I'm curious if getting https://github.com/Vitallium/qtwebkit/issues/5 and https://github.com/ariya/phantomjs/issues/13942 in PhantomJS will make the hack less hacky. Might still have to do some scaling but at least not so much JS hackery.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://varamtrust.com/cure.php?iqtn>

 

klaus@hebsgaard.dk

**Comment by DeviaVir** [comment]
webkit PR reopened against a new repo:
https://github.com/annulen/webkit/pull/515

https://github.com/ariya/phantomjs/pull/13942 still depends on that PR to be merged first...

**Comment by Vitallium** [comment]
Landed in master! Thank you, @DeviaVir !

**Comment by av01d** [comment]
What happened to this? 2.1 is the latest version that's downloadable? The 2.5 branch seems gone?
How/when can we use page.devicePixelRatio = x ?

**Comment by DeviaVir** [comment]
@av01d https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
