### ISSUE TITLE
HTTP Status code only available if onResourceReceived fires.

### ISSUE THREAD

**Issue by Corion** [ariya/phantomjs#11257]
The HTTP status code of a response is only available if onResourceReceived fires. onResourceReceived only seems to fire if the response has a body.

It would be nice if either onResourceReceived also fires if there is no body to the response, or if onResourceError fires with any 4xx or 5xx HTTP status and makes that status code available.

The following script demonstrates the behaviour:

```
var page = require('webpage').create();
var server = require('webserver').create();
var service = server.listen(8090, function (request, response) {
  // Return empty body
  var parts= /^\/(\d+)(.*)?$/.exec(request.url);
  var code= parseInt( parts[1], 10 );
  var body= parts[2];
  response.statusCode = code;
  response.write(body);
  response.close();
});

page.onResourceReceived = function(res) {
//  console.log(JSON.stringify(res, null, 4));
  console.log('onResourceReceived ' + res.status);
};

page.onResourceError = function(res) {
//  console.log(JSON.stringify(res, null, 4));
  console.log('onResourceError ' + res.status);
};

console.log('Loading HTTP 404 with empty response body');
page.open('http://localhost:8090/404', function() {

console.log('Loading HTTP 404 with filled body');
page.open('http://localhost:8090/404/with_body', function() {

  server.close();
  phantom.exit();
})
});
```

**Comment by pritamkarmakar** [comment]
Is there any workaround or any plan to fix this? I'm facing the same issue.

**Comment by TiddoLangerak** [comment]
This issue also seems to affect actual webpages rendered by PhantomJS (2.1.1). I use [prerender](https://github.com/prerender/prerender) to render an Angular app for SEO, but from within the app I don't get a proper status code when no response body is set. The `XmlHTTPRequest` object has the status code set to 0, and additionally it without body the `xhr.onerror` function is called, instead of `xhr.onload`.
