### ISSUE TITLE
PhantonJS ignores proxy on 127.0.0.1 host

### ISSUE THREAD

**Issue by reed1** [ariya/phantomjs#11342]
Try to open a page, example

var page = require('webpage').create();

page.open('http://localhost:8080', function () {
    page.render('shot.png');
    phantom.exit();
});

with pahntomjs --proxy cmd options, then it won't pass through the proxy. I have proxy and webserver both on local

Thanks

**Comment by garytaylor** [comment]
I vote for a change here - perhaps a --no-proxy option which defaults to 'localhost,127.0.0.1' or something like - this way, it will not break anyone's test suite etc...  Those wishing to use something like puffing-billy or agile-proxy can then set no-proxy to ''.  At the minute, I am having to find the test runner machine's ip address and make the request via that as both localhost and 127.0.0.1 do not go via the proxy :-(

**Comment by rac2030** [comment]
using the actual IP of the localhost works that the proxy gets triggered.
I though first that this issue is related to what I experienced but it seems my issue was just that I need to set the proxy trough cli args from ghostdriver as the selenium way does not work.

**Comment by lkwg82** [comment]
+1

**Comment by itslittlejohn** [comment]
+1. to clarify what @rac2030 said above about using the IP since I was confused at first: Setting the application host to use either my local ip or my hostname is the workaround that worked for me. At first I tried setting my proxy host to my ip/hostname but that didn't do anything. Might not be confusing for all, but my use-case has the proxy and application on the same machine.

**Comment by abourget** [comment]
No progress on that ? I'm stuck in here with no support for `no_proxy`..

**Comment by shankarkc** [comment]
Can you please bring this to closure.  Its an important feature. All enterprise use proxy.  To reach our test environment we need to skip proxy.

**Comment by ro31337** [comment]
This one is very important for everyone

**Comment by lkwg82** [comment]
@ro31337 So, have you already offered a patch?

**Comment by rac2030** [comment]
Given there is an easy workaround, I don't see it as an urgent feature (and it's not a bug as this is the default behaviour and if then it would need to be changed in QT itself like done in PR #12703 which has never been merged.
Note that changing 3d party library code in a project itself introduces a maintenance overhead whenever you want to update the library to a newer version.

QT Documentation states it clearly:

> Network proxy is not used if the address used in connectToHost(), bind() or listen() is equivalent to QHostAddress::LocalHost or QHostAddress::LocalHostIPv6.

Another option instead of the changes on the QT core libs like odne in the pending pull request could be just adding an option like --localhost-proxy which would just intercept the navigate method and first evaluates the local IP and replaces localhost or 127.0.0.1 with it. More thoughts on implementation would be on the cases where the machine has no network connection at all or multiple IP's.
