### ISSUE TITLE
SVG stroke-opacity ignored

### ISSUE THREAD

**Issue by S11001001** [ariya/phantomjs#11381]
In 1.9.0 Windows:

Output of following with `rasterize.js` should be three-tone, no black, as indeed it is to PNG, but PDF is two-tone with a black border.

``` html
<!DOCTYPE html>
<html>
<title>Translucent lines</title>
<style type="text/css">
rect{
  fill:#b4da55;
  stroke:#000;
  stroke-width:10px;
  stroke-opacity:0.3;
}
</style>
<body>
<svg width="120px" height="120px" viewBox="0 0 120 120">
  <rect x="10" y="10" width="100" height="100"/>
</svg>
</body>
</html>
```

**Comment by zowers** [comment]
test: https://output.jsbin.com/cadegawumi

**Comment by zowers** [comment]
works fine in phantomjs 2.1

**Comment by robinfhu** [comment]
Note:
We encountered a similar issue where SVG lines with stroke-opacity set would render as pure black lines in the PDF.

It turns out the PDF viewer has an effect on this.  Using Google Chrome's PDF engine, the svg lines would be black.

But using Safari's PDF engine, the svg lines would have the right opacity.

**Comment by migueloop** [comment]
I'm having the same issue, any workaround?
