### ISSUE TITLE
page.render('/dev/stdout', { format: 'pdf' });

### ISSUE THREAD

**Issue by zatlite** [ariya/phantomjs#11725]
Hi, 

I'm trying to use page.render('/dev/stdout', { format: 'pdf' }); command in resterize.js file in Windows and I have a problem with the data output coming back with encoding errors. 

My original goal was to get the file generated on the fly instead of saving to disk on my server. After reading the git hub source, I found that the file is still being saved to disk temporarily anyway. That's ok. The main issue is the encoding errors in my result from stdout. After searching the github code, I think maybe I may have found the point where the encoding problem is introduced?

https://github.com/ariya/phantomjs/blob/4989445e714bb97fe49ef8c00ccbce8b6cfbfbb0/src/webpage.cpp

Line 926: ((File *)system->_stdout())->write(QString::fromAscii(ba.constData(), ba.size()));

Do you think if you change fromAscii to fromUtf8, my encoding issues will be resolved?

I wish I could do the change myself and test but I can't build the source because I don't have all the required tools installed on my PC. 

Could you test this for me please?

**Comment by eddydarell** [comment]
Hello, Sorry to pick up this thread so late, I thought it'd be better to take it from here instead of creating a new one. I have the same issue as @zatlite but what I do is run the PhantomJs command from PHP with exec. Then I get the output via the $out second parameter of exec() like this: 

`$response = exec($cmd, $out)`

My problem is that, the data is returned as an array built from the PDF raw string. I tried using 

`implode(PHP_EOL, $out)`

to rebuild the raw file and serve it as PDF but then, I get an empty PDF file. The file has the same number of pages as it should but comes blank with some weird characters as title.

I suspect the charset to be th reason behind this behavior but don't know how to go around this limitation. 
Any help will be greatly appreciated.

PS: The script is running on Linux CentOS.
