### ISSUE TITLE
Phantomjs does not respect CSS border width

### ISSUE THREAD

**Issue by marcusg** [ariya/phantomjs#12188]
I use phantomjs to generate a pdf from a given html page. 

The html looks like this (screenshot from Chrome)
![html](https://cloud.githubusercontent.com/assets/198369/2839253/1d9b8752-d044-11e3-8a3a-a7968e847033.png)

and the generated pdf
![pdf](https://cloud.githubusercontent.com/assets/198369/2839261/3c967cac-d044-11e3-8013-8e565a014d88.png)

The CSS:

```
.table
  table-layout: fixed

  > thead
    border-bottom: 1px solid black

  > tbody
    border-bottom: 1px solid black
```

Any ideas how to resolve this?

**Comment by gsalvati** [comment]
1pt didn't worked for me. Same as 1px, less then 1pt not showing in PDF

**Comment by shchedrakov** [comment]
I have same problem. I can't to find solve.

**Comment by tacone** [comment]
I found a workaround, but it's time costly. Phantom refuses to print borders of less than 1px ignoring the fact that 1px will be scaled up significantly when printing on an A4 paper sheet.

So you are forced to give it a viewport as large as a a4 sheet.
```
phantomjs rasterize.js http://example.com/myreport myreport.pdf '2480px*3508px'
```
If you do that, you'll get the thin lines. The problem you get is that the text and images will be very small when printed. Thus, you have use to pump up the base font size, then use relative unit sizes, like em, for everything: margins, padding, heights etc.

Also try not to use media query, but rather a `.print` class, so that you will not interfere with native browser printing.

**For example:**

Set up a wrapper element (or just use the body if you prefer) and reset the font sizes and optionally paddings and margins:

```
.wrapper {
    font-size: 15px;
    line-height: normal;
}
.wrapper * {
    font-size: inherit;
    line-height: normal;
}

.print .wrapper {
   font-size: 400%;
}
```

In descendant elements, use percent units for font sizes, and ems for all the rest:

```
.wrapper h4 {
    font-size: 200%;
    padding: 1.5em;
    border: 1px solid black; /* this border will be thin */
}
```

This is the only working workaround that I found.

**Comment by palidanx** [comment]
@tacone I tried to run a viewport of A4, and I still don't get any lines.  What px were you using for your border? I'm trying to generate a .5px and a .25px border

**Comment by tacone** [comment]
@palidanx you can't. Use 1px as the minimum, and increase the viewport size if the borders are too thick.

**Comment by PierBover** [comment]
I've tried setting huge values for `width` and `height` and I still get the same thick lines with `border: 1px solid black;`. Anything less than `1px` won't render.

I'm using `2550px` x `3300px`for the page config (letter format at aprox 300dpi). I've tried using the CSS `zoom` rule but it won't change the border thickness.

Here with `zoom: 1;`

![image](https://user-images.githubusercontent.com/226483/35524823-c5005e70-04f0-11e8-8934-91e505df757b.png)


Here it is with `zoom: .5;`

![image](https://user-images.githubusercontent.com/226483/35524796-b15169dc-04f0-11e8-9d5a-1dbacc50cc78.png)

I don't know how @tacone did it unless maybe he is printing to an image instead of PDF.
