### ISSUE TITLE
Stack trace does not show column when exception occurs.

### ISSUE THREAD

**Issue by fmmontas** [ariya/phantomjs#12289]
Whenever a javascript exception occurs the stack trace only contains the line number and not the column, ex. 'path/to/file/someFile.js:56' where 56 is the line number. Without the column number source maps will not currently work. Given an exception occurs 'path/to/file/someFile.js:56:11' where line number is 56 and column number is 11 seems like the common format.

**Comment by jtomaszewski** [comment]
+1 - currently I need to use Chrome in Karma, because sourcemaps don't work in PhantomJS :(

**Comment by leonardfactory** [comment]
:+1:

**Comment by dtryon** [comment]
+1

**Comment by alexbuijs** [comment]
+1

**Comment by andras-tim** [comment]
+1

**Comment by decates** [comment]
+1

**Comment by claycephas** [comment]
+1

**Comment by danieljsinclair** [comment]
+1

**Comment by axelpale** [comment]
+1

**Comment by absynce** [comment]
It looks like the change would be in the [Webkit source (JavaScriptCore/runtime/Error.cpp)](https://github.com/ariya/phantomjs/blob/f7ecf6ccb91249a89c19769a4818a13f065cb2d6/src/qt/src/3rdparty/webkit/Source/JavaScriptCore/runtime/Error.cpp#L179). 

Does PhantomJS maintain a version of Webkit or should this be resolved upstream? I see related tests which makes me think it's maintained here.

I'll contribute if this is an approved feature since it's in the Issues list. Or should I go through the mailing list per the [Contribution Guide](https://github.com/ariya/phantomjs/blob/master/CONTRIBUTING.md)?

**Comment by matthauck** [comment]
:+1:

**Comment by matthauck** [comment]
Hmm. Looks like this may not be a phantomjs issue anymore. Just updated to phantomjs-prebuilt 2.1.5, and column numbers are now present!

**Comment by WolfgangKluge** [comment]
Hmm, I've still the same problem with phantomjs 2.1.1 (phantomjs-prebuilt 2.1.14) on windows.

I see `phantomjs://code/test.js:4 in global code` when I execute the script

```javascript
setTimeout(function () {
    phantom.exit();
}, 0);
throw '';
```

Still no column numbers (and therefore no chance to get source maps to work correctly)..

**Comment by JoshSchreuder** [comment]
> Hmm, I've still the same problem with phantomjs 2.1.1 (phantomjs-prebuilt 2.1.14) on windows.

Same here. If I run the tests via Karma in Chrome / Firefox the stacktrace uses sourcemaps correctly.

**Comment by benlakey** [comment]
@Vitallium I don't think this is fixed, so any chance of re-opening it?

**Comment by rmartins90** [comment]
+1
