### ISSUE TITLE
onload event not fired for stylesheets

### ISSUE THREAD

**Issue by Artur-** [ariya/phantomjs#12332]
``` javascript
var page = require('webpage').create();

var f = function() { console.log("done"); phantom.exit();};                    
page.onConsoleMessage = function(msg) {
  console.log('Console: ' + msg);
};
page.open("http://localhost:8888/onloadtest.html", f);
```

should output

```
Console: LOADED
done
```

when onloadtest.html is

``` html
<html>
<head>
<link type="text/css" rel="stylesheet" href="http://localhost:8888/styles.css" onload="console.log('LOADED');"/>
<body>
Hello
</body>
</html>
```

Instead, the output is only

```
done
```

**Comment by call-a3** [comment]
Pushing this because I also need it. 
I found previously closed issues stating that this is not a bug in phantomjs because webkit didn't support the onload event, but now that it does this should really also be included in phantomjs.

**Comment by pmorch** [comment]
The really bad part about this lack of support is that it is sort-of supported and it therefore isn't possible to detect lack of onload support for &lt;link&gt; tags using [a very popular approach](http://perfectionkills.com/detecting-event-support-without-browser-sniffing/), apparently  [used by jQuery, Prototype.js, Modernizr](http://stackoverflow.com/a/1262811/345716). Basically the problem is that:

    > 'onload' in document.createElement('link');
    true

Please either fix onload support or remove the `onload` key from link elements so that lack of support is detectable.

**Comment by mildfuzz** [comment]
Is there a work around for this? Waiting for CSS to load is a great way to ensure injected JS applications look good at launch.

**Comment by mildfuzz** [comment]
the only solution I have found is to use slimerjs instead

**Comment by gurdiga** [comment]
+1

**Comment by sumbach** [comment]
I observe the same behavior (`onload` callback not executed for `<link>` elements) with PhantomJS 1.9.8 on Ubuntu 12.04.5.

This seems to have been resolved in a subsequent release: `onload` is executed as expected with PhantomJS 2.1.1 on Ubuntu 12.04.5 and OSX 10.11.6 El Capitan.

**Comment by sumbach** [comment]
Is this a duplicate of #11721?
