### ISSUE TITLE
Header and footer 'wrapping' webpage content

### ISSUE THREAD

**Issue by Batistleman** [ariya/phantomjs#12590]
I would like to build something like this:

```
header: {
    height: "1cm",
        contents: phantom.callback(function(pageNum, numPages) {
            return "<div style='border: 2px solid;border-radius: 25px;'>";
        })
    },
    footer: {
        height: "1cm",
        contents: phantom.callback(function(pageNum, numPages) {
            return "</div>";
        })
    }
```

this to create a 'wrapping' effect on each page. 

But somehow it seems to auto-close the div before the body of the page.

Any ideas on how I could solve this?

**Comment by matths** [comment]
+1 for the idea

I think, the markup returned in the phantom.callback function, is even not interpreted taking the markup and css of the rendered page into account. That's why you use inline styles inside of your returned html.

The wrapper idea is nice, but would probably break as soon as a page break is inside another element like a long list or table. So it would also be just fine to have some custom element directly injected?
