### ISSUE TITLE
Text antialiasing and transparency

### ISSUE THREAD

**Issue by gewfy** [ariya/phantomjs#12761]
Hi!
Text antaliasing against transparency seems to have a black matte. As described in this issue #11276  but only with the text rendering. On Linux using PhantomJS 1.9.8. 
![0de8a9ca-6f0e-11e4-975c-9254ec310c88](https://cloud.githubusercontent.com/assets/474066/5139682/55eee34c-7161-11e4-8e33-d425393c65b5.png)
White text on transparent background:
![b0f5957e-6f0e-11e4-97dc-b786ac4ef6eb](https://cloud.githubusercontent.com/assets/474066/5139686/5a9b5e34-7161-11e4-935d-bccf4dc87238.png)
On tinier texts it makes the text almost unreadable
![untitled-1](https://cloud.githubusercontent.com/assets/474066/5139762/bdaeca32-7162-11e4-94f5-d0a20c9bffc3.png)

Thank you!

**Comment by mds2** [comment]
@gewfy I don't work on phantomjs, but a coworker pointed me to this bug, and I think I've seen something like it before.

When producing images with partial transparency, they can either be produced with "premultiplied alpha" or without premultiplied alpha.  Premultiplied alpha means you represent [a, r, g, b] by storing [a, a*r, a*g, a*b] instead of by storing [a, r, g, b].  It makes a bunch of compositing operations faster and more straightforward to think about.

The problem is that blending images that use premultiplied alpha requires a different blend operation than blending images that do not use premultiplied alpha.  If one makes a mistake, and blends a premultiplied alpha image as if it were produced without premultiplied alpha, one tends to get a dark halo around the partially-transparent portions of the image.

For a discussion of how this affects rendering in OpenGL, see, for instance
http://blog.rarepebble.com/111/premultiplied-alpha-in-opengl/

A google search for "premultiplied alpha dark halo" produces quite a few hits.

**Comment by gewfy** [comment]
Wow thank you! 
It is still weird that this only affects text rendering but not regular transparent graphics. I solved it by adding an invisible CSS glow to the text. This seems to force premultiplied alpha :)
```css
{
  text-shadow: 0 0 1px rgba(255, 255, 255, 0.1);
}
```

**Comment by mds2** [comment]
We have also noticed what may be inconsistencies between how text rendering and transparent graphics are blended.  We are unsure as to whether the issues with antialiased borders of non-text graphical elements are due to something we are doing, or due to something phantomjs is doing.

**Comment by mds2** [comment]
By the way, just for clarity's sake : PhantomJS was already rendering anti-aliased text in a manner consistent with premultiplied alpha.  Whatever you were using the composite the resulting images of text was what was unaware of premultiplied alpha.

I am not familiar with this invisible CSS shadow hack, but the same coworker who alerted me to this issue tells me that it is a common front-end web dev trick.  I am baffled as to what it does, what it fixes, and why it works.

**Comment by tomjakubowski** [comment]
coworker @mds2 mentioned here :-)

While I just barely grok "premultiplied alpha", I'll say that we found far fewer (maybe even "no") "weird" artifacts at the boundaries between the "transparent background" and "solid-colored page elements" in PNGs generated by scripting an internal CEF-based renderer. Until this bug is resolved, if all you need are web page screenshots with a transparent background, it might be worth investigating CEF/Blink as a backend.
