### ISSUE TITLE
Override DNS resolution for CDN tests

### ISSUE THREAD

**Issue by nodomain** [ariya/phantomjs#12872]
Hi,
I need to test a web app both via CDN and the origin. So I need a way to override the IP for a certain hostname - I want to avoid modifying the /etc/hosts file for this.
Perhaps something like https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDNSName

Thanks!
Fabian

**Comment by acdha** [comment]
I believe this is possible using 1.2 or later using [`onResourceRequested`](http://phantomjs.org/api/webpage/handler/on-resource-requested.html) to change the URL using an approach like this:

```js
var page = new WebPage();

page.onResourceRequested = function(requestData, networkRequest) {
    var match = requestData.url.match(/https?:\/\/www[.]example[.]org\//);

    if (match != null) {
        var cdnUrl = requestData.url.replace('www.example.org', 'www.example.org.the-new-cdn.example.net');
        // console.log('Rewriting request:', requestData.url, cdnUrl);
        networkRequest.changeUrl(cdnUrl);
        networkRequest.setHeader('Host', 'www.example.org');
    }
};
```

I'm still confirming that this covers all of the details – note in particular the `setHeader()` call to preserve the original host header – but it's looking like this could be as simple as a documentation update to make it easier to find.

**Comment by fengidri** [comment]
@acdha  I think this is good way.

**Comment by FlorianBador** [comment]
Unfortunately no this is NOT a good way because this is not transparent for the page. The page will know what the new URL is, and any relative path (e.g. an image file in a css) will be based on the new URL.
I hope someone will answer the original question because I am looking for the same thing. I want to have all resolutions return 127.0.0.1 (then of course I won't check certificates for SSL).
Thanks!
