### ISSUE TITLE
Do you need crashy sites for testing PhantomJS?

### ISSUE THREAD

**Issue by kyledrake** [ariya/phantomjs#12910]
I may have some web sites to give you to test PhantomJS' ability to defend itself against crashy/stalling sites.

Neocities has put together a timeout system that will kill an attempt to take a screenshot if it's taking too long: https://github.com/neocities/neocities/blob/master/workers/screenshot_worker.rb#L8

We also have a fast-running monit instance that will very quickly kill the process if memory or CPU gets out of hand.

We used something that didn't work as well before, but now we use screencap (https://github.com/maxwell/screencap), which works far better and uses this JS script: https://github.com/maxwell/screencap/blob/master/lib/screencap/raster.js

So anyways, we will flag sites that are stalling or crashing PhantomJS to prevent us from taking screenshots of them in the future, which means we've compiled a pretty good database of test cases by neccessity.

If you would like me to do the work to compile those sites for the core team, let me know and I will figure out a way to do that.

**Comment by kyledrake** [comment]
Not an issue, so closing.

**Comment by Vitallium** [comment]
Can you e-mail them to me? I think we can do something about it.

**Comment by ariya** [comment]
I think this is actually a valid issue (i.e. the crashing). If this can be turned into a script that loads the series of those web site, it will be beneficial for our testing.
Take a look at https://github.com/ariya/phantomjs/blob/master/test/run-tests.py. Perhaps what we need it a collection of those load-this-page-it-will-crash scripts and place them under a new `crashes/` directory and have that `run-tests.py` run it (not by default since it will block our usual development). Thoughts?
