### ISSUE TITLE
phantomjs tries to access keychain on OSX

### ISSUE THREAD

**Issue by therauli** [ariya/phantomjs#12960]
I recently updated to phantomjs 2.0 and was very supprised when my scripts started asking for keychain access. After some digging around it seems that phantomjs is running an old version of Qt that has this bug: https://bugreports.qt.io/browse/QTBUG-30434

I guess updating Qt would fix the issue.

**Comment by EdenVicary** [comment]
I've had this issue as well.

**Comment by kenorb** [comment]
The same here.

> phantomjs wants to use your confidential information stored in "tracking.foo.com" in your keychain.
> [Always Allow] [Deny] [Allow]

Testing with: `sudo fs_usage phantomjs`:

    20:44:11.578789  open              F=15       (R_____)  /Users/user/Library/Keychains/login.keychain                                                                                                                                      0.000005   phantomjs.2800752

All I have is simple Python unittest opening my Home page:

    self.site.get(self.base_url + "/")

I wanted to implement [Headless Selenium Testing](https://realpython.com/blog/python/headless-selenium-testing-with-python-and-phantomjs/), however it isn't headless, as the test freezes and ask for the confirmation in the popup.

Related:

- [OSX is repeatedly asking for login keychain password](http://apple.stackexchange.com/q/124591/22781)

Any suggestions how to disable it? As workaround, I'll try to remove my problematic records, however I don't see how this solves the issue.

**Comment by kenorb** [comment]
Found some workaround using [Apple Script](http://apple.stackexchange.com/a/184901/22781) and clicking Allow button to run my Selenium tests, but it isn't a good solution:)

Tested latest PhantomJS (`brew install phantomjs --HEAD`), I have both qt 4.8.6 and qt5 installed (`brew install qt5`), but the problem still persist. I was hoping that phantomjs would use qt5 where the problem is supposedly fixed, but I'm not sure how to check which version it's using. Based on #10448, sounds like it should use qt5, so I'm not sure what I'm doing wrong.

**Comment by mariozig** [comment]
I just saw this happen for the first time.  It looks like if the phantomjs process is killed then the dialog goes away as well.  I'm using phantomjs in a background job/queue scenario so luckily if i have jobs fail due to not responding to that dialog they are retried a few times. 

If anyone is in a similar situation then just killing the process and expecting it to try may be another workaround. :/

**Comment by jborden** [comment]
I have the same problem. This bug essentially make phantomjs unusable on my Mac OS X (10.9.5) system. =(

**Comment by Vitallium** [comment]
This issue will be resolved in the next major Qt upgrade (5.5).
Tracking issue #13377

**Comment by ariya** [comment]
@therauli Can you try it again with PhantomJS 2.1?

**Comment by therauli** [comment]
Sorry for the extremely late response. Unfortunately I have changed jobs so I don't have access to the code anymore.

**Comment by obromios** [comment]
I am experiencing this problem using poltegeist with capybara in rails 4.2.  I have Qt 5.5.1_1 and phantomJS 2.1.1.  The problem only happens intermittently, only when I run my full test suite.  Of course when it does happen, it is when I am really needing the test run to have finished.
