### ISSUE TITLE
Phantomjs crash with dump file

### ISSUE THREAD

**Issue by hasanyousuf** [ariya/phantomjs#13062]
We have been using phantomjs from more than an year and more than 1000 runs. It has started crashing frequently. Please suggest how can we stop crashing phantomjs.

Here is crash dump file https://drive.google.com/file/d/0B5qscIaWmDHKNWRyVkpBeVBvdU0/view?usp=sharing

**Comment by allquixotic** [comment]
That is not a useful crash dump; it doesn't contain any info that can be used to guess at a reason for the crash. You need to get all the debugging symbol packages from your distro and install them (the exact process for this is distro-specific, so you'd need to research that), for all libraries and modules that PhantomJS uses from the system. Then, if you have downloaded PhantomJS from the web, you'll need to recompile it from source. Otherwise, if you're using PhantomJS from a distro repository, you'll have to get the debugging symbols from that repository.

As a last-ditch effort, if you can't get adequate debugging symbols for a full instrumented backtrace, you will have to compile PhantomJS from source as a debug build (unstripped binary).

In order for anyone else to have any hope of providing an answer as to why it crashes, you would have to:

1. Run the unstripped binary (or the binary that corresponds to your installed debugging symbols) under the `gdb` debugger: `gdb --args ./phantomjs pjs-args...` 
2. Type `start`, press enter, type `c`, press enter, then make phantomjs crash
3. Type `bt full` and press enter
4. Send us the output from `gdb` (all of it), plus:

 - Your Linux distro and architecture
 - How you installed or compiled PhantomJS
 - The version of PhantomJS you're running
 - A description of what you did or where your script or Selenium was in the execution when it crashed

Even then, we'd probably still need access to the full page source of whatever webpage/application caused the crash.

Have you tried PhantomJS 2.0?
