### ISSUE TITLE
Phantomjs 2.0: phantomjs giving incorrect CSS computed style

### ISSUE THREAD

**Issue by surenderthakran** [ariya/phantomjs#13102]
Phantomjs Version: `2.0`
Bug Reproduction:
```javascript
   var page = require('webpage').create();
   var system = require('system');

   var ARG_URL = system.args[1];
    page.open(ARG_URL, function(status) {
     if(status === "success") {
          setTimeout(function () {
             page.evaluate(function(){
                console.log(window.getComputedStyle(document.getElementsByClassName("u01logo")[0]).getPropertyValue("display"));
             });
             return phantom.exit();
          }, 5000);
      }
  });
```

Terminal Command: `phantomjs phantomscript.js http://www.oracle.com/`

Output: `none`
Correct Output: `block`

Tested In: `1.9.0, 1.9.8, 2.0`

When checked in browser the same console command says the element is `display:block`.
I also generated a screenshot of the page. The screenshot displays the element it claims to be `display:none;`

**Comment by JamesMGreene** [comment]
Was the screenshot you generated a JPG or a PDF?  Very important distinction there.

If it was a PDF, I would say that you should not assume that Phantom is returning the wrong value in your use case because it may be that the page is being served differently for Phantom's userAgent string (NOT uncommon for websites to do this, for some weird reason...).  I'd suggest setting the userAgent to be a common userAgent string like Firefox's or Chrome's.

If it was a JPG, then yes, it sounds like there is a probably a bug in the CSS engine.

**Comment by surenderthakran** [comment]
@JamesMGreene  Actually it was a png. But thanx setting the userAgent and viewportSize did fixed the issue.

**Comment by JamesMGreene** [comment]
Sure, same idea.  :+1:

**Explanation of my troubleshooting logic:**
Using the standard image formats does the equivalent of a screen capture, whereas rendering a PDF does the equivalent of a system print (which changes the CSS media type and sometimes causes alternate stylesheets/rules to be applied).
