### ISSUE TITLE
not able to build phantomjs2.0 on ubuntu 14.10

### ISSUE THREAD

**Issue by nareshk355** [ariya/phantomjs#13229]
below is the error encountered while running the "./build.sh --confirm --silent"

breakpad/src/client/linux/handler/exception_handler.h:178:26: error: field âfloa                                                                                        t_stateâ has incomplete type âgoogle_breakpad::_libc_fpstateâ
     struct _libc_fpstate float_state;
                          ^
Makefile.phantomjs:7011: recipe for target 'crashdump.o' failed
make[1]: *** [crashdump.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/test/travis/phantomjs-2.0/phantomjs/src'
Makefile:38: recipe for target 'sub-src-phantomjs-pro-make_first-ordered' failed
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

**Comment by nareshk355** [comment]
gcc version if that helps...
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/powerpc64le-linux-gnu/4.9/lto-wrapper
Target: powerpc64le-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.1-16ubuntu6' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libsanitizer --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-ppc64el/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-ppc64el --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-ppc64el --with-arch-directory=ppc64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-secureplt --with-cpu=power7 --with-tune=power8 --disable-multilib --enable-multiarch --disable-werror --with-long-double-128 --enable-checking=release --build=powerpc64le-linux-gnu --host=powerpc64le-linux-gnu --target=powerpc64le-linux-gnu
Thread model: posix
gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6)

**Comment by Vitallium** [comment]
This `Target: powerpc64le-linux-gnu`
We don't support PowerPC. Make sure you're using the correct GCC version.

**Comment by nareshk355** [comment]
could you please let me know which specific gcc version to use.

**Comment by sowani** [comment]
Hi Vitallium,

I am working with my colleague nareshk355 on this. We understand that phantomJS is not ported to PowerPC, but we are trying to port it ourselves to PowerPC. Once PhantomJS is ported to PowerPC, we will be committing it back to PhantomJS community.

We do have GCC ported to PowerPC, however if there is a need to port specific GCC version to PowerPC in order to get PhantomJS ported, we are willing to do that. Could you please let us know the specific GCC version you need to get PhantomJS compiled?

Any help in this regard is highly appreciated.

Thanks,
Atul.

**Comment by Vitallium** [comment]
@sowani It's not about a specific version of GCC, it's all about specific features on PowerPC (architecture).
In order to compile PhantomJS for your specific arch you need:
* Create `mkspec` for your platform (https://github.com/ariya/phantomjs/tree/master/src/qt/qtbase/mkspecs)
* Make sure Qt compiles successfully for it
* Webkit already has support for PowerPC, and it should be configured automatically, but you might be need to adjust some build flags.

**Comment by sowani** [comment]
Thank @Vitallium! Yes, I think it would be better to create another issue to track PowerPC port, so we will create it now.

I understand that PhantomJS has dependency on Qt and Webkit and unless they are ported first, PhantomJS cannot be compiled on PowerPC. However, if it is not required for core functionality of PhantomJS, can it be somehow bypassed? This would enable us to work on core functionality first and tackle the Qt porting and support related functionality later.

Best regards,
Atul.

**Comment by Vitallium** [comment]
Closed. PowerPC is not supported target platform yet.
