### ISSUE TITLE
Pages from scribd are scrambled.

### ISSUE THREAD

**Issue by kenorb** [ariya/phantomjs#13230]
I've tested the following example:

```
$ phantomjs rasterize.js http://www.scribd.com/doc/15049545/Saxo-Trader-2-Walk-Through page.pdf
```

However the generated page looks scrambled. Not sure what's the reason.

![screen shot 2015-05-13 at 23 06 04](https://cloud.githubusercontent.com/assets/266306/7622184/e12a9f8c-f9c4-11e4-8b5b-e6169bf2db82.png)

On the left it's original page, on the right it's rasterized PDF page.

**Comment by DaniGuardiola** [comment]
That happens because phantomjs must be using the media "print", I'm working on a phantomjs script to download scribd documents and I got this exact same problem.
It seems like they are working on fixing it or at least there are a lot of requests, but at the moment I'm trying to remove the media attributes (without success yet, I don't know why).

**Comment by kenorb** [comment]
@DaniGuardiola I've tried [scribd-dl](https://github.com/kenorb/binfiles/blob/master/scribd-dl) script in shell, but without success.

**Comment by DaniGuardiola** [comment]
@kenorb hmmmm I got it almost working! https://github.com/DaniGuardiola/scribd-downloader
There are two problems:
- Viewport width is not being applied. This is probably a stupid mistake on the API usage, didn't really take a look at it.
- The document is empty when rendered, no text and no images. This will be a tough one, Scribd seems to be blocking somehow the rendering and I don't know how, but I'm almost there. Once it works I will try to get the different pages and stuff, and later I will try to use pdf instead of pngs converted to pdf so the text can be selected. Can you take a look at it? Maybe you can find what's wrong.
Cheers.
