### ISSUE TITLE
LocalFileDetector - PhantomJs 2.0 GhostDriver Windows8

### ISSUE THREAD

**Issue by chiragmewada** [ariya/phantomjs#13302]
# PHP CALL

```
 $file_input = $this->driver->findElement(WebDriverBy::xpath(".//*[@id='uploader']/form/input[3]"));
    $file_input->setFileDetector(new LocalFileDetector);
    $file_input->sendKeys($image);
```
# ERROR

PHP Fatal error:  Uncaught exception 'WebDriverException' with message 'JSON decoding of remote response failed.
Error code: 4
The response: 'Error - incompatible type of argument(s) in call to _uploadFile(); candidates were
    _uploadFile(QString,QStringList)'
' in /var/www/craiglist/php/v3/lib/remote/HttpCommandExecutor.php:241
Stack trace:
#0 /var/www/craiglist/php/v3/lib/remote/RemoteWebDriver.php(491): HttpCommandExecutor->execute(Object(WebDriverCommand))
#1 /var/www/craiglist/php/v3/lib/remote/RemoteExecuteMethod.php(36): RemoteWebDriver->execute('uploadFile', Array)
#2 /var/www/craiglist/php/v3/lib/remote/RemoteWebElement.php(338): RemoteExecuteMethod->execute('uploadFile', Array)
#3 /var/www/craiglist/php/v3/lib/remote/RemoteWebElement.php(299): RemoteWebElement->upload('/var/www/craigl...')
#4 /var/www/craiglist/php/v3/includes/classes/clposter_basic.class.php(478): RemoteWebElement->sendKeys('/var/www/craigl...')
#5 /var/www/craiglist/php/v3/includes/classes/clposter_basic.class.php(487): clposter_basic->uploadImag in /var/www/craiglist/php/v3/lib/remote/HttpCommandExecutor.php on line 241

**Comment by gunfrank** [comment]
I get the same error when trying to attach file using the Codeception framework (with PhantomJS running as GhostDriver).

Anyone have idea how to work around this?

**Comment by chiragmewada** [comment]
You need to remove 'multiple' from input tag to make it work
e.g 
&lt;input type="file" name="img" multiple&gt;

Following is how i manage to remove using php
$this->driver->executeScript("document.getElementsByName('file')[0].removeAttribute('multiple')", array());

**Comment by gunfrank** [comment]
`<input name="MultipleUploadForm[file]" id="MultipleUploadForm_file" type="file">`

There's no "multiple" in the input tag of the upload field I'm struggling with. Having said that, it does accept multiple files to be uploaded when doing it manually. I suppose it's still the same issue, yet I can't bypass it by removing the 'multiple' from the input tag.

Any ideas?

**Comment by aniolekx** [comment]
same for me, Codecpetion 2.1.2, PhantomJS 2.0.0

**Comment by mknecht** [comment]
I looked into this [a fair bit](http://muratknecht.de/blog/post/uploading-files-phantomjs-ghostdriver-python/).

**Short:** Use the `UselessFileDetector`. Make sure your files are available on the machine where PhantomJS is running.

**Longer:** As [mentioned on SO](http://stackoverflow.com/questions/32270958/file-uploading-error-in-codeception), this does not happen when running with the PhantomJS driver directly. That's because [Ghost Driver PR#324](https://github.com/detro/ghostdriver/pull/324) implemented the `uploadFile` command incorrectly. Instead of taking a zipped file in the  `file` parameter [as the Selenium server does](https://github.com/SeleniumHQ/selenium/blob/2ac6a7dd708c13018d529b1c372b1f0353d41fed/java/server/src/org/openqa/selenium/remote/server/handler/UploadFile.java#L54), it's [expecting two parameters](https://github.com/ariya/phantomjs/blob/b483dd673a1ca589ff10c5f73dfea1e43bfa3225/src/ghostdriver/request_handlers/session_request_handler.js#L206): `selector` and `filepath`.

What does `uploadFile` do? The Remote WebDriver must assume that PhantomJS is on another machine. Therefore, it needs not only to send the path of the file to the browser (PhantomJS), but also the file itself. The latter is what `uploadFile` does.

The **workaround** is to not try to upload the file in the first place, but just send the path. 

For **Python** this means setting the `_is_remote` attribute:

    is_remote = webdriver._is_remote
    webdriver._is_remote = False
    webdriver.find_element_by_css_selector('input').send_keys(filepath)
    webdriver._is_remote = is_remote

Looking at Facebooks **PHP** version of the remote driver, the decision of whether or not to use `uploadFile` [hinges on the `$this->fileDetector`](https://github.com/facebook/php-webdriver/blob/cbd8347d40592276d7a5649f54db621b32338a34/lib/Remote/RemoteWebElement.php#L304). This means for the duration of `sendKeys` you need to switch to the `UselessFileDetector`, which [is the default](https://github.com/facebook/php-webdriver/blob/cbd8347d40592276d7a5649f54db621b32338a34/lib/Remote/RemoteWebElement.php#L53). To be sure:

    $file_input = $this->driver->findElement(WebDriverBy::xpath(".//*[@id='uploader']/form/input[3]"));
    $file_input->setFileDetector(new UselessFileDetector);
    $file_input->sendKeys($image);

**If your PhantomJS actually runs on a different machine**, regardless of which remote driver you use you need to make sure that the files are actually available on the remote server *on the path that you are sending*.
