### ISSUE TITLE
In V2.0.0 html table heading not repeated across pages in PDF

### ISSUE THREAD

**Issue by rwankar** [ariya/phantomjs#13324]
In version 1.9.8 the <thead> row was repeated on each page without any special setting. What do I need to do to get the same in 2.0?

**Comment by trygveaa** [comment]
I discovered this issue as well, and saw that it has been addressed a few times before: #211 #344.

I saw that some of what #344 added was missing in master, and tried readding that. This makes the header/footer appear on the next page. However, the other content is not shifted down, so the header appears on top of the table on the next page, instead of above it.

What I have done so far is available here: https://github.com/trygveaa/phantomjs/tree/repeat-thead-tfoot-page-break

**Comment by trygveaa** [comment]
Correction: It seems like the problem with the header overlapping the table was because of some css styles in the page I was testing.

I tested with a page without styles. For this page, everything seems to be correctly drawn.

**Comment by rwankar** [comment]
Thanks @trygveaa. I assume this means that I have to download your source and build it myself? When will the fix make it into the standard build?

**Comment by trygveaa** [comment]
Yes, if you want it now, you have to build it yourself. If you're asking me, I don't know when it will be included (I don't have any relation to phantomjs). I opened pull request #13331, so we will just have to wait and see.

**Comment by rwankar** [comment]
Hello Trygve,

I finally got around to building my own PhantomJS with your patch. But I am seeing that the table header overlaps with the page content.

Please see attached. Any ideas what could be wrong?

**Comment by szdmr** [comment]
Do you have binaries for Windows?

**Comment by trygveaa** [comment]
@rwankar: Hi, sorry for not replying to you. I didn't need this after all, so I lost a bit of interest, and then forgot about it.

I also experienced that overlapping issue when I tested my patch. Though, I tried with a page without any CSS, and then I didn't experience the problem. So I'm not sure what the problem is, and if it's a bug with my patch or if it can be fixed with CSS. I haven't investigated this further, so can't help you with it unfortunately.

@szdmr: I assume you mean binaries with my patch, since you ask here? I don't have it at least, and would doubt anyone else has.

**Comment by sonu27** [comment]
Any updates on this? We are experiencing this when using https://github.com/marcbachmann/node-html-pdf

**Comment by JoeyLi-1** [comment]
@sonu27 @rwankar  I fixed this issue based on 2.1.1 since the latest version 2.5 does not work at all when rendering PDF. If you want this feature the binaries are here: (https://github.com/JoeyLi-1/phantomjs-1) release 2.1.15. 

source code: (https://github.com/JoeyLi-1/qtwebkit) if you are interested).

I might create a PR in main branch if I could figure out how to work with the phantom - 2.5

**Comment by krutkowski86** [comment]
+1

**Comment by rwankar** [comment]
@JoeyLi-1 thanks for the update. I'll give this a try.
