### ISSUE TITLE
phantom.addCookie always adding leading dot to domain

### ISSUE THREAD

**Issue by storzinc** [ariya/phantomjs#13409]
With this test script:

``` javascript
phantom.addCookie({name:'x', value:'y', domain:'example.com'});
console.log(JSON.stringify(phantom.cookies));
phantom.exit();
```

I'm getting this output:

```
[{"domain":".example.com","httponly":false,"name":"x","path":"/","secure":false,"value":"y"}]
```

Note that there is a dot added to domain, such cookie will be sent not only to example.com but also for all subdomains

**Comment by JamesMGreene** [comment]
Hmm....

So, this one is a little trickier [and, in many ways, unfortunately correct] than you might suspect.

As noted in [a very good StackOverflow answer](http://stackoverflow.com/a/1063760/471696) (**emphasis** added in a few spots):

> There is a distinction between the _Domain_ attribute value and the **effective domain**: the former is taken from the `Set-Cookie` header field and the latter is the interpretation of that attribute value. According to the [RFC 2965](http://tools.ietf.org/html/rfc2965), the following should apply:
> - If the _Set-Cookie_ header field **does not** have a _Domain_ attribute, the **effective domain** is the domain of the request.
> - If there is a _Domain_ attribute present, its value will be used as **effective domain** **(if the value does not start with a `.` it will be added by the client).**

In order words, the behavior you are seeing is as if the cookie you specified were instead being specified verbatim by the HTTP server that is hosting the corresponding webpage.  Unfortunately, that means that it is explicitly setting the "Domain" attribute of the Cookie (as if in a `Set-Cookie` HTTP response header), which browsers are required to interpret as having a leading `.`, _regardless of if the value actually contains a leading `.`_.

I agree that this behavior is extremely annoying as I just recently ran into that myself in a different situation (and not involving PhantomJS).

That said, in order to accommodate what you are looking for while using the `phantom` object's `addCookie` method, we will need to either change the method signature or else add another Phantom-only property to the object you pass that will instruct Phantom to only set that cookie for the exact matching domain and to _not_ set the "Domain" attribute when setting the cookie on an actual WebPage instance.

For example, some theoretical API usage:

```js
// Separate arg for targeted domains
phantom.addCookie({ name: 'x', value: 'y' }, ['example.com']);

// Extra property "implicitDomain"
phantom.addCookie({ name: 'x', value: 'y', domain: 'example.com', implicitDomain: true });

// Separate arg to indicate that the domain should be implicit, NOT explicitly setting the "Domain" attribute
phantom.addCookie({ name: 'x', value: 'y', domain: 'example.com'}, true);
```

**Comment by JamesMGreene** [comment]
**Good News:** Actually, looks like there is already an underlying method implementation for what I proposed (not that surprising, since the browsers follow this concept already): [`CookieJar::addCookieFromMap(cookie, url)`](https://github.com/ariya/phantomjs/blob/6897baae33bf8648ceb2667da850c3609cd8b11f/src/cookiejar.cpp#L152)

**Bad News:** Unfortunately, that underlying method isn't currently exposed as part of the public API.


If we exposed it verbatim, its usage would look like this:

```js
phantom.addCookieFromMap({ name: 'x', value: 'y' }, 'http://example.com');
```

**Comment by JamesMGreene** [comment]
@ariya @Vitallium @detro @zackw: Feedback?

**Comment by zackw** [comment]
I'm afraid I don't know much about cookies and cookie-related web
standards, but is there any reason this can't be an extension to the
existing `addCookie` API rather than an entirely new `addCookieFromMap`
function?  The latter isn't a terribly well-motivated name if you're not
familiar with the implementation.

**Comment by storzinc** [comment]
For me it seems more intuitive if the `domain` attribute will be interpreted verbatim, so that it will be possible to pass to `phantom.addCookie` the value that you previously get from `phantom.cookies`.
But if that will pose some compatibility problems, this syntax also looks good:

```javascript
phantom.addCookie({ name: 'x', value: 'y', domain: 'example.com'}, true);
```

**Comment by JamesMGreene** [comment]
@storzinc I think nearly all web devs, including myself, would whole-heartedly agree with you but, alas, that's not how cookie domains work in browsers. It's a very confusing and not well known behavior.

**Comment by JamesMGreene** [comment]
@zackw I was forgetting that Qt C++ supports default parameters, so yes, we can just update the signature to include an optional second parameter (domain/URL string).

**Comment by curiouslybrown** [comment]
+1

**Comment by siboulet** [comment]
> - If the Set-Cookie header field does not have a Domain attribute, the effective domain is the domain of the request.
> - If there is a Domain attribute present, its value will be used as effective domain (if the value does not start with a . it will be added by the client).

I sometime end up having two exact cookies, one having the leading dot in the Domain attribute, the other doesn't. When that happens I think Phantom is getting confused and will happily keep the two cookies (and I'm not sure which one is used).

This seems to happen when a cookie that did not have a Domain attribute is being updated by an explicit Set-Cookie that has a Domain attribute set but without the leading dot.

**Comment by cedson** [comment]
I'm hitting this same issue while working with phantomJS/GhostDriver in testing a specialized-browser-based system - I find myself needing to fork a session where the same seed cookie values are used (from the base session) in starting the forked session - but then updated upon first response within the forked session.

What I see is that I'm able to copy the cookies from the base session into my new phantomJS/GhostDriver instance, but then when the Set-Cookie comes back in the first response, updating the seeded cookies to their new, session-independent values (a 302, as it happens) - I end up with duplicate cookies in the subsequent outbound Request.  (as the two cookies appear to be from different domains:  domain.suf versus .domain.suf)

Is there any interim solution I can explore?  (is wiring to onUrlChanged a viable option for stripping duplicate cookies on-the-fly?)

**Comment by gunnar-ifp** [comment]
This is a bit late but after overhauling our internal cookie management (no leading dots :)  I stumbled over the fact that we pass these to PhantomJS and weird things may happen:
First: The current RFC is 6265. The goal of this specification was to make things simpler and it did so.

For domains: It abolishes the leading dot altogether. That leading dot is not allowed anymore.
Instead of it it introduces a "host-only-flag" that is stored with the cookie and tells the user agent if the cookie was sent with domain (host-only-flag = false) or without (host-only-flag = true). The Matching algorithm is so that if host-only-flag==true, then one simply equals the request domain and the cookie domain, otherwise one does the sub domain comparison.

Now if one looks into Chrome developer tools, one can see that leading dot still there. That is ok. And phontomJS can do it, too. Because one can use that leading dot as host-only-flag:

When storing cookies from a server response, for cookies without domain, simply store the request domain/ip. For cookies with domain attribute: remove any leading dot from the domain, then simply add that leading dot back to the domain if it is not an IP address. Of course one can skip the remove/add if it's a domain with a leading dot, but that is just a technical detail. Then do the domain matching as described below to verify that the cookie is actually valid to store.

Later, when setting up phantomJS for a new request, a suffix substring match against the request domain for cookies with leading dot domain and an equals match for cookies with domains without dots is all that is necessary.

When storing a cookie programatically, i.e. setting up phantomJS for a request, then phantomJS should not use any logic to alter the cookie domains given to it. If the user supplies a cookie with a leading dot domain, then this means that this cookie has no host-only-flag and if the domain is an ip address or domain without leading dot, then this is a host-only domain.

Only by doing it this way - differ between http responses setting a cookie and the user setting a cookie can all this ambiguity and all the bugs go away.
