### ISSUE TITLE
Array sort. Phantomjs swap the arguments in the comparator

### ISSUE THREAD

**Issue by alvaroortega** [ariya/phantomjs#13509]
I'm currently having problems with Phantomjs. My issue is kind of related with the one mentioned here: https://github.com/ariya/phantomjs/issues/11090.

Phantomjs is swapping the arguments in the comparator method as you could see running this simple test:
```javascript
(function(){
  var array = [3,1,6,2,8];
  console.log('Array:', array);

  var comparator = function(val1,val2){
    console.log("val1:", val1);
    console.log("val2:", val2);

    if(val1 <= val2) return -1;
    if(val1 > val2) return 1;

    return 0;
  };

  var sorted = array.sort(comparator);
  console.log('Sorted:',sorted);
})();

phantom.exit(0);
```

The final result is OK in this case but, we can't have the behaviour we desire for an algorithm that is trying to order objects with some particularities. Due to the mentioned swapping, we get different results running it in Chrome and Phantomjs.

**Comment by zackw** [comment]
This is not something we have any control over.  The code that does the sorting is taken, unmodified, from JavaScriptCore, and *it* just calls either [`qsort(3)`](http://linux.die.net/man/3/qsort) or [`mergesort(3)`](http://linux.die.net/man/3/mergesort) from the C library.

The specification for `Array.prototype.sort` (http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.sort) does not say anything about ordering of the arguments to the comparison function.  What it *does* say is that the comparison function is required to be reflexive and symmetric; in particular, if `a < b` according to the comparison function, then it must also be the case that `b > a` according to the comparison function.

So I regret to say that the bug is in your code.  You *must* write your comparison function such that it works correctly regardless of whether its arguments are "swapped".

**Comment by alvaroortega** [comment]
Indeed. That is why I said we had a "particular case". 
We solved our problem before writing this. I just say that this "discrepancy"  between the runners could cause problems if, for instance, you are ordering an array of objects. If you assume the value you are using to sort the array, could be null for some components,... you could have different results depending on the runner you use.

Of course there is nothing that cannot be sorted using alternatives :)

All the best.
