### ISSUE TITLE
phantomjs has crashed using bbc-wraith to take screenshot

### ISSUE THREAD

**Issue by abioneperhobby** [ariya/phantomjs#13535]
on lubuntu 15.04 i installed https://github.com/BBC-News/wraith to make screenshot comparisons. wraith uses phantomjs to take screenshots. 

this is the log

root@qa-test-1:/var/www/html/testpages/wraith# wraith history configs/config.yaml 
Creating Folders
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7ce2c7ea-4c77-5da9-0dce477c-6e2f8e2c.dmp
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7ce2c7ea-4c77-5da9-0dce477c-6e2f8e2c.dmp
Segmentation fault (core dumped)
Snapping http://localhost/testpages/player4x/immagini/immaginenormale.html at width 1280
Segmentation fault (core dumped)
Snapping http://localhost/testpages/player4x/immagini/immaginenormale.html at width 1920

and this is the dump http://www.filedropper.com/7ce2c7ea-4c77-5da9-0dce477c-6e2f8e2cdmptar 

i think problem is resolution.

if i downside screenshot resolution, it works.

**Comment by zackw** [comment]
We apologize for not responding to this sooner.

This is more of a support request than a bug report - we can't do anything constructive about it with the amount of information you've provided, and it may well not be a bug in PhantomJS at all.  (For instance, since it crashes only when you take high-resolution screenshots, perhaps the problem is you are running out of RAM?) If you still have a problem, please bring it up at either

 * the official [PhantomJS users mailing-list](http://groups.google.com/group/phantomjs)
 * [Stack Overflow](http://stackoverflow.com/questions/tagged/phantomjs) (with `phantomjs` tag)

where we can more easily work through the problem with you and figure out whether there's genuinely a bug.

If you have not read it yet, please check also a few tips on [Effective Q&A](https://github.com/ariya/phantomjs/wiki/Support).
