### ISSUE TITLE
How to add Specific Route in Phantomjs Webserver?

### ISSUE THREAD

**Issue by surajdalvi** [ariya/phantomjs#13550]
Hi
I am using **webserver** to listen request on particular host. I write ipaddress:port to listen request. But I want to add specfic route into it. for e.g -**127.0.0.1:8080/test**  How I do that please help me?

**Comment by ricardograca** [comment]
I think you'll have to parse the `request.url` part to see which path is being requested by the client and then handle it yourself.

However, the web server module was never intended as a fully featured web server, so it only has basic functionality, but enough for most simple communication needs. What I'm trying to say is that if you need to handle different routes and have middleware, you're better off creating a proper Express server with Node.js and then interfacing that with PhantomJS.

**Comment by zackw** [comment]
We apologize for not responding to this issue sooner.

Ricardo is correct.  There is no built-in support for routing in the webserver module, you have to do everything by hand.

In addition, the webserver module really only exists because the WebDriver protocol uses HTTP.  It has a number of serious technical problems and we discourage its use.

Finally, as a matter of project policy: This issue tracker primarily serves as the tool to report and track bugs, defects, and development tasks.
For general question, code review request, build problem, or other related discussion, please post it to either:

 * the official [PhantomJS users mailing-list](http://groups.google.com/group/phantomjs)
 * [Stack Overflow](http://stackoverflow.com/questions/tagged/phantomjs) (with `phantomjs` tag)

If you have not read it yet, please check also a few tips on [Effective Q&A](https://github.com/ariya/phantomjs/wiki/Support).
