### ISSUE TITLE
Phantomjs script can't build angularjs app.

### ISSUE THREAD

**Issue by gardemm** [ariya/phantomjs#13586]
Hi!

There's a website using angularjs 1.4. Usual browsers are supported and the code works fine, but phantomjs can't build it.

I put into the console at the phantomjs bin folder `$ ./phantomjs renderbot.js 19003 http://site.com/`. 

This is the renderbot.js script:

```
var system = require('system');
var args = system.args;
var os = require('system').os;

if (args.length < 3) {
  console.log("Missing arguments.");
  phantom.exit();
} else {
    var server = require('webserver').create();
    var port = parseInt(args[1]) || 8888;
    var urlPrefix = args[2];

    var getPage = function(url, callback) {
        var page = require('webpage').create();
        page.settings.javascriptEnabled = true;
        page.settings.loadImages = false;
        page.settings.localToRemoteUrlAccessEnabled = true;
        page.settings.XSSAuditingEnabled = true;

        page.open(url, function() {
            setTimeout(function() {
                page.evaluate(function() {
                    $('meta[name=fragment], script').remove();
                });

                callback(page.content);
                page.close();
            }, 3000);
        });
    };

    server.listen(port, function(request, response) {
        response.headers = {
            'Content-Type': 'text/html'
        };

        var regexp = /_escaped_fragment_=(.*)$/;
        var fragment = request.url.match(regexp);

        var url = urlPrefix + '#!' + decodeURIComponent(fragment[1]);

        statusCode = (fragment[1] == '404' || fragment[1] == '/404') ? 404 : 200;

        getPage(url, function(html) {
            response.statusCode = statusCode;
            response.write(html);
            response.close();
        });
    });
}
```

When I try to open `localhost:19003` nothing is displayed and there's a constant loading bar.

**Comment by zackw** [comment]
Sorry for the delay getting back to you about this.

There are two possibilities here.  It might be a bug in Webkit, or it might be a bug in the webserver module, which is ... troublesome.  Please try to reproduce the problem without using the webserver module (do something like `examples/rasterize.js` instead).

If the problem is still present without the webserver module, then this is a bug in Webkit, and we're going to need you to take it up with the Webkit developers directly (https://www.webkit.org/quality/reporting.html).  We don't have the manpower to fix Webkit bugs ourselves.

If the problem goes away with the webserver module, then we might be able to do something about it, but we need a complete, self-contained, minimized test case- *everything* that will be needed to reproduce the bug, but nothing that is superfluous.
