### ISSUE TITLE
PhantomJS unable to interpret GUI objects through Xpath 

### ISSUE THREAD

**Issue by amiya-pattnaik** [ariya/phantomjs#13616]
hi,
We have selenium code which is up and running different browser such as Safari, Chrome, FireFox. Our new requirement is to run those test cases on headless mode. Hence we have asked to use PhantomJS. While executing test cases we noticed that PhantomJS is not able to identify objects which has reference through Xpath and test cases failed. We are getting below errors.

[RuntimeError: RuntimeError
     (NoSuchElement:7) An element could not be located on the page using the given search parameters.
     Problem: Unable to find element with xpath '//*[@id='header']/descendant::div[@class='header-left']/h1'

     Callstack:
     -> element("//*[@id='header']/descendant::div[@class='header-left']/h1")
     -> waitFor("//*[@id='header']/descendant::div[@class='header-left']/h1",35000)
]

[RuntimeError: RuntimeError
     (NoSuchElement:7) An element could not be located on the page using the given search parameters.
     Problem: Unable to find element with xpath '//*[@id='localCurrencySelection']/select'

     Callstack:
     -> element("//*[@id='localCurrencySelection']/select")
     -> waitFor("//*[@id='localCurrencySelection']/select”,35000)
]

We also tried setSize ()  and client.Pause() with different parameter but none of them are working. Basically it is not identifying the objects at run time
Where as same test cases are working perfectly on real browsers. Our test cases are purely on NodeJS. 

Please advice us how to proceed. 
thanks,
Amiya

**Comment by zackw** [comment]
First, please make sure you are using PhantomJS 2.0.  1.9.x has many bugs and is no longer developed.

Second, XPath issues are without question WebKit's fault.  We do not have the manpower to fix WebKit bugs ourselves, or to cherry-pick fixes.  Therefore, if you can reproduce the problem using 2.0, then please try to reproduce it using a nightly build of WebKit.  If it does reproduce using nightly WebKit, please report it to the WebKit developers directly.   Conversely, if the problem does *not* reproduce using nightly WebKit, then it will eventually be fixed in PhantomJS when we pick up a newer version.  (Unfortunately, there is no schedule for that.)
