### ISSUE TITLE
No document title returned

### ISSUE THREAD

**Issue by derwaldgeist** [ariya/phantomjs#13634]
I really like PhantomJS, but one thing is driving me mad: Getting the title of a page does only work on a few web pages. On the others, PhantomJS does not return a title, although it is definitely available in the page. This happens with both approaches described in the examples, i.e.
```js
title = page.title;
```
and
```js
title = page.evaluate(function() {
   return document.title;
}
```
I have absolutely no clue why it works for some pages and doesn't work for others. One sample page is http://de.wikipedia.org, which has the title at the top of the <head> section. The same applies to http://www.heise.de. Maybe this problem is related to these titles containing Non-ASCII characters (German umlauts)?

**Comment by zackw** [comment]
I can't reproduce this problem.

    $ ./bin/phantomjs examples/loadspeed.js http://de.wikipedia.org
    Page title is Wikipedia – Die freie Enzyklopädie
    Loading time 699 msec

    $ ./bin/phantomjs examples/loadspeed.js http://www.heise.de
    Page title is heise online - IT-News, Nachrichten und Hintergründe
    Loading time 5474 msec

loadspeed.js uses the `page.evaluate` technique.

It's possible that this is because the markup on Wikipedia and Heise has changed and no longer provokes the bug.  Could you please attempt to construct a *minimal, self-contained* test case that demonstrates the problem?  That would be a complete PhantomJS controller script, plus a web page whose title cannot be retrieved.

(Also, if you're still using PhantomJS 1.x, please try 2.0.  2.0 has a significantly newer version of Webkit and it's conceivable that you are tripping over a bug in the old version.)

**Comment by derwaldgeist** [comment]
Thanks for your answer. I was sick the last days and could not come back to your reply. Will try to reproduce!
