### ISSUE TITLE
-webkit-calc not supported in JS

### ISSUE THREAD

**Issue by nathancahill** [ariya/phantomjs#13658]
According to this page, `-webkit-calc` is supported: http://phantomjs.org/tips-and-tricks.html

However:
```
> ele.style.width = '-webkit-calc(100% - 10px)';
> ele.style.width
''
```

**Comment by zackw** [comment]
Are you using 1.9.x? `-webkit-calc` might be one of the things introduced with the substantial upgrade to Webkit in 2.0.

If it doesn't work in 2.0, then the problem is ultimately that PhantomJS is not keeping up with Webkit at the moment - I think the version in 2.0 is currently about a year old.  We will eventually pick up a browser core with better `calc()` support, but we're not going to start cherry-picking web platform features. I regret I don't have a time frame for you.
