### ISSUE TITLE
Phantomjs v2, consume huge memory+cpu, after throwing exception.

### ISSUE THREAD

**Issue by awakmu** [ariya/phantomjs#13707]
Finally, I can reproduce this issue.
Guys, this issue make my 8G dedicated server, crashed.
This issue, suddenly eat +80% of cpu+ram.
This issue is not reproducible in v1.9.8.

Code to repeat this issue:

```
var page = new WebPage();

page.onResourceReceived = function(resource)
{
    console.log('Response (#' + resource.id + ', stage "' + resource.stage + '"): ' + JSON.stringify(resource));
};
page.onConsoleMessage = function(msg)
{
    console.log("console: " + msg);
};
page.onLoadStarted = function()
{
    console.log("load started");
};
page.onLoadFinished = function()
{
    console.log("load finished");
};
var customOnError = function(msg, trace)
{
    var msgStack = ['ERROR: ' + msg];
    if (trace && trace.length) {
        msgStack.push('TRACE:');
        trace.forEach(function(t) {
            msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function + '")' : ''));
        });
    }

    var allMsg = msgStack.join('\n');
    console.error(allMsg);

    phantom.exit();
};
page.onError = customOnError;
phantom.onError = customOnError;
page.onResourceTimeout = function(data)
{
    console.error("timeout");
    console.error(JSON.stringify(data));
    throw new Error(2);
};
try
{
    console.error("start");
    throw new Error(1);
}
catch(error)
{
    console.log(error.message);
    phantom.exit();
}
```

**Comment by ahamid** [comment]
I think I have a similar issue, although I am not sure yet what steps reproduce it.  I can track it down to a line in my tests, but reverted to `1.9.20` from `2.1.1` seems to fix it as well.

This does not appear to be just a "leak".  Tests complete, but phantomjsj process does not return to console and continues to consume memory at the rate of ~100mb/s.  I think it initally OOMed my whole machine because I wasn't paying attention...

After updating `gulp-mocha-phantomjs` I noticed runaway memory usage.  It appears to be due to the dependency change from

` "phantomjs": "1.9.1 - 1.9.7-15",`
to
`"phantomjs-prebuilt": "^2.1.3",`

There is no `v1.9.7-15` tag, and github claims `v1.9.20` contains `v2.1.1` changes (which I'm confused by).  In any case, reverting the dependency, which results in a `v1.9.20` package appears to fix the runaway memory consumption at end of tests, and leave several lines of (apparently innocuous) output:

```
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///path/to/my/project/base/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js. Domains, protocols and ports must match.
```

```
$ cat /etc/redhat-release 
Fedora release 20 (Heisenbug)
$ uname -a
Linux t440s 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by awakmu** [comment]
Calling console.error, from phantom.onError callback, will cause nested call.
Just don't do it in version 2.
