### ISSUE TITLE
Multi language support for screenshots

### ISSUE THREAD

**Issue by manishmshiva** [ariya/phantomjs#13719]
How can I grab a screenshot of an arabic page? eg. http://monitor.situ8.io/analytics/563b3c9f988f682f2b3174dc/900/900/back

**Comment by zackw** [comment]
This should just work, provided you have all the necessary fonts installed.  I can't give you instructions for that because it depends on your operating system. If you are sure you have all the necessary fonts installed, and the page renders correctly in a regular browser running on the same computer, and you're using PhantomJS 1.9, it would be worth trying 2.0 -- it has a much newer version of Webkit, which may have improved the rendering of Arabic, but I don't know that for s

(This is a support question, not a bug report.  In the future, please post support questions to the phantomjs users mailing list, not to the bug tracker.)
