### ISSUE TITLE
Error: Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by boltozavr** [ariya/phantomjs#13736]
The problem: When our app send PUT, DELETE non-Cross-domain requests to the server, we get this error. Not always, but sometimes(about 1 of 7). Sometimes error occurs, sometimes not. 

We tried to disable web-security with flags, but this does not solve issue

We tried to set server allow cross-domain requests, but this does not solve issue too.

**Comment by karnelius** [comment]
Hello.
We had the same problem. Our tests work with cucumber-js + selenium-webdriver + phantomjs.
To repeat this bug you need: 
1) First open any page with ajax requests, e.g.:  browser.get('http://example.com');
2) Then wait page load, but not wait ajax responses;
3) Then go to other page or refresh page,  e.g.:  browser.get('http://example.com/newpage');
Result: all ajax responses were return with the error "Origin is not allowed by Access-Control-Allow-Origin". 

Problem was fixed when we started wait ajax responses. e.g.:  browser.wait()

**Comment by codeviking** [comment]
We ran into this as well, and were able to deterministically reproduce it.  As reported, this occurs when:

1. You load a page (using `page.open(...)`), which has Javascript that kicks off an asynchronous (XHR) request on the client.

2. You use `page.open()` before said request is complete to change the page.

In this case, Phantom appears to cancel and/or terminate the request with a cross-domain error, even though there's no actual error (Phantom is likely just discarding the handler).

I'd guess it has something to do with the way that Phantom closes and/or terminates pending XHR requests when changing the page.  

In our case, we ultimately had to add code specific to our application that "silences" this error, since it's not a true exception (in our case the error was bubbling upwards and causing failures while executing automated tests):

```javascript
if(
  util.isBrowser()
  && err.crossDomain
  && 'userAgent' in navigator
  && navigator.userAgent.indexOf('PhantomJS') !== -1
) {
  // fail silently
  return;
}
```
