### ISSUE TITLE
[Follow-up] '--proxy-type=none' works on Windows, but not always on Linux

### ISSUE THREAD

**Issue by kriegaex** [ariya/phantomjs#13746]
Refers to #13745 which was closed too quickly and I cannot even comment on it anymore, which I think is a rather rude way to handle users.

@zackw, I am very sorry to bother you with this but how can I use PJS2 on Linux if you do not even offer an official Linux build such a long time after 2.0 was published? I am afraid I have to insist to get some help or analysis here because I use the latest stable version with an official Linux build. This is a real issue, not just a support question.

Can you at least offer a workaround? I have no power to decide to migrate our Jenkins server from Linux to another platform.

**Edit:** I cannot use 2.0 in order to test if it works better because in 1.9.8 it already works on Windows. It does not on Linux which I cannot test because there is no version 2.0 for that platform. Can you see my dilemma? It is not that I do not want to test 2.0 or am too lazy. It is just unavailable.

**Comment by zackw** [comment]
I closed and locked your earlier bug report because we really need you to take your follow-up support questions to the [user mailing list](https://groups.google.com/group/phantomjs-users).

Unofficial builds for Linux are available from several sources, which we will tell you about on the [user mailing list](https://groups.google.com/group/phantomjs-users).
