### ISSUE TITLE
/tmp/213cd8f1-e797-c479-4290246f-779c9225.dmp

### ISSUE THREAD

**Issue by roenfa** [ariya/phantomjs#13769]

**Comment by roenfa** [comment]
/tmp/213cd8f1-e797-c479-4290246f-779c9225.dmp

**Comment by zackw** [comment]
I'm afraid we did not get your dump file -- but that's OK, because, contra what it says when PhantomJS crashes, dump files are almost always useless to us.  (Soon there will be a new version that doesn't bother with them.)

Here are some things you can try:

* Upgrade to 2.0 if you aren't already using it.  2.0 includes many, many crash fixes.
* Attempt to find the _smallest possible webpage_ that still makes the crash happen.
  * Can you cut out all the JavaScript?
  * Can you replace all the text with lorem ipsum?
  * Can you simplify how you are _running_ PhantomJS against the test site?
  * Can you make the crash happen without using WebDriver?
* Test a [Webkit nightly build](http://nightly.webkit.org/): most PhantomJS crashes are due to bugs in Webkit, and we don't have the manpower to fix those ourselves, but we do regularly update our copy of Webkit.  If you can make a Webkit nightly crash, [report that directly to them](https://www.webkit.org/quality/reporting.html).

I'm going to close this bug report now, because we can't do anything useful with it.  If you need more help, ask for help on either

 * the official [PhantomJS users mailing-list](http://groups.google.com/group/phantomjs)
 * [Stack Overflow](http://stackoverflow.com/questions/tagged/phantomjs) (with `phantomjs` tag)

If you do manage to narrow your problem down to something that seems to be definitely a bug in PhantomJS itself (not Webkit), please file a _new_ bug report rather than reopening this one; it is easier for us to keep track of things that way.
