### ISSUE TITLE
Chinese chars in page url's hash，phantomjs open has problem

### ISSUE THREAD

**Issue by supersha** [ariya/phantomjs#13791]
Code like below show:

```
var pageUrl = "http://xs.sm.cn/?uc_param_str=dnfrpfbivelasscpntnw&ch=sale#!/homepage?fetch=score!!ucuid=702376302!!smuid=10041519!!nickname=好久不见APL!!avatar=19";

var page = require('webpage').create();

page.settings.userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53';

page.open(pageUrl, function(status){
        console.log(status);
        var url = page.url;
        console.log(url);
        phantom.exit();
});
```

when open this page, the `page.url` with output : ' http://xs.sm.cn/?uc_param_str=dnfrpfbivelasscpntnw&ch=sale#!/homepage?fetch=score!!ucuid=702376302!!smuid=10041519!!nickname=????APL!!avatar=19' ，and then page render wrong。

I try to set `phantom.outputEncode='utf8'`，but it is not work。

**Comment by zackw** [comment]
I believe this is another manifestation of bug #12216.  If so, that is fixed by pull request #12233, which will be included in the upcoming 2.0.1 release.  If you are able to build and test the development sources and confirm whether your problem is solved, that would be helpful.  I am going to close this bug report now, but if your problem is _not_ solved, feel free to reopen it.
