### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by egetmanenko** [ariya/phantomjs#13804]
Subj.
[FA04FA8B-E01A-40E4-92C1-77913D50BDFA.dmp.zip](https://github.com/ariya/phantomjs/files/60251/FA04FA8B-E01A-40E4-92C1-77913D50BDFA.dmp.zip)

**Comment by zackw** [comment]
I'm sorry to say that a crash dump all by itself is useless to us.

1. We are about to release version 2.1, which contains many, many crash fixes.  Please build and test the latest development version if you can; if you can't do that, please stay tuned for the release, then test that.
1. If the crash still happens with 2.1, we don't want the crash dump (indeed, 2.1 won't even produce crash dumps); we want a *complete, self-contained test case*.  The smallest possible webpage + PhantomJS script that still crashes.

Because we can't do anything with this as is, and because it's very likely that the newer version will fix your problem, I am going to close this bug report.  If you still have a problem with 2.1 it is probably simpler to file a new bug.
