### ISSUE TITLE
Symbols for version 2.1.1 linux 64 missing & dump file

### ISSUE THREAD

**Issue by spyjo** [ariya/phantomjs#13944]
Hello,

I have some crash of phantomjs to analyse, but the symbols archive is missing on https://bitbucket.org/ariya/phantomjs/downloads , can you please upload it for linux x64 for 2.1.1 ?

Also, how to force phantomjs to generate the dump file ? actually it does not seems to generate it when I have the crash (I use the precompiled version 2.1.1 for linux 64)

Thank you

**Comment by zackw** [comment]
This is intentional. We don't want crash dumps or stack traces anymore, they are almost always useless. (You shouldn't even have gotten a crash dump with 2.1.1, we took that code out.) Please put your efforts into developing minimal, self-contained test cases instead. There's a draft of new bug reporting instructions on the new discussion forum, please have a look at that and kibitz: http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22

**Comment by spyjo** [comment]
Ok thanks.
I have no specific test case, PhantomJS crash randomly for the exact same code, using the compiled version or the version I build myself.
All with segfault, memory corruption, and things like this.
I will try to find the problem.
