### ISSUE TITLE
Phantom 2.x not rendering font-style property (bold & italic) when using font-face

### ISSUE THREAD

**Issue by paulwalczewski** [ariya/phantomjs#13984]
Hello,

we have stumbled upon an issue with Phantom, since we migrated to 2.x branch - styled fonts (font-style) are not rendered as they should (applied style is not visible).

I've prepared a fiddle:
https://jsfiddle.net/ghzs1egj/5/

If you put that through phantom you will see that bold is actually not applied.

We have tried different declarations of font-face, different font types - and nothing helps.
Using separate font files for different declaration can't be treated as a solutions for 2 reasons:
- this would bloat file transfer (3-4x more fonts to handle...) 
- not all fonts are avaiable in their italic/bolded/bolded+italic versions.

In Phantom 1.9x it was working.

**Comment by tykarol** [comment]
+1

**Comment by jacdobro** [comment]
+1

**Comment by therealmikz** [comment]
+1

**Comment by KoderoPL** [comment]
+1

**Comment by rcetra** [comment]
+1

**Comment by miase** [comment]
+1

**Comment by nitroo88** [comment]
+1

**Comment by simplecooler** [comment]
+1

**Comment by chrisber** [comment]
Maybe related issue #13742

**Comment by thisispaul** [comment]
+1

**Comment by geri777** [comment]
+1

**Comment by myaffee** [comment]
+1

**Comment by gwu** [comment]
+1

**Comment by oleghind** [comment]
+1

**Comment by SwapnilKamdar** [comment]
+1

**Comment by ziemkowski** [comment]
+1

**Comment by ziemkowski** [comment]
+1

So while this messes up web fonts served by Google Fonts, TypeKit appears to work as expected:

![image](https://cloud.githubusercontent.com/assets/704098/17531262/22433d78-5e49-11e6-9436-e676e045569f.png)

**Comment by ziemkowski** [comment]
Okay so this makes sense now. PhantomJS v2 uses a new version of WebKit, which is causing the Google Fonts CDN to serve `*.woff2` files, which is apparently where the problem is. If you fake an ancient user agent, the endpoint will send you an older file which still renders correctly in PhantomJS v2.

**Workaround:** I was able to get weights and styles to render correctly by setting my user agent to Firefox 27::
```js
page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0'
```

This causes the Google Fonts CDN to serve `*.woff` files and now we have font weights and styles again (note that Arima Madurai _does not_ offer italics):
![image](https://cloud.githubusercontent.com/assets/704098/17674969/bcd1e8ca-62f5-11e6-9e90-0a2b457d2a3c.png)

**Comment by raghu185** [comment]
Considering the issue has been reported over a Year back. Any new updates on this ? , I am still facing this issue in 2.1.1, are there any plans to fix this.

**Comment by ricardo** [comment]
+1

**Comment by evandrojr** [comment]
+1

**Comment by youhyunkim** [comment]
+1

**Comment by fvoordeckers** [comment]
+1

**Comment by hellokatili** [comment]
+1

**Comment by sandersu** [comment]
+1

**Comment by bjornburn** [comment]
+1

**Comment by pranjalworm** [comment]
+1

**Comment by PatrickRWright** [comment]
+1
