### ISSUE TITLE
<select> option don't popup after click on it

### ISSUE THREAD

**Issue by futurist** [ariya/phantomjs#14017]
When do below 3 steps:

1. open a page in phantomjs that has only a select box (position is 10,10)
2. send a `click` event on it( `page.sendEvent('click', 11,11,'left')` )
3. `page.render` to get an image of the page

**What's the result?**
The select box in image not popup it's options

**What should be expected?**
Like real select box, the options should show in popup

Although the options can be get via JS, but It's important when test by compare image with target image, or when playback user click event.

**Comment by zackw** [comment]
Thank you for your bug report.

You don't say which version of PhantomJS you are using.  If you are still using 1.9.x versions, please test 2.1, which has a newer version of Webkit that fixes many bugs of this variety.

If 2.1 still exhibits the problem, this is a bug in Webkit.  We do not have the manpower to fix Webkit bugs ourselves; we do, however, regularly pick up updated versions.  Please report this bug directly to the Webkit developers, following the instructions at https://webkit.org/reporting-bugs/.

Since there's nothing we can do about this, we will be closing this bug report now.

**Comment by futurist** [comment]
Above tested both in 1.9.8 and 2.1.1

**Comment by futurist** [comment]
Please consider reopen this issue, since it's very basic function of a browser, **click select box and show up options**, I have the confidence that don't need to test in WebKit.

Consider this should be an issue in Qt or something else, related to **event generating and sending**

**Comment by zackw** [comment]
Please believe me when I say that this cannot possibly be a bug in anything but Webkit.

**Comment by futurist** [comment]
The bug reported here:

https://bugs.webkit.org/show_bug.cgi?id=154447

**Comment by futurist** [comment]
There's a update about this issue, from webkit.org:

> Looks like phantomjs is based on QtWebKit, which is not one of the ports supported at webkit.org. Please see <https://trac.webkit.org/wiki/BuildingQtOnLinux>.

>The below comment from phantomjs issue discussion seems like a good guess to me, although in this case, this becomes a phantomjs bug. Since it is phantomjs that advertises offscreen drawing capability, it is that project's responsibility to make it work.

>...

**Comment by zackw** [comment]
This is another strike against continued use of Webkit in this project, I think.  If they're not prepared to fix their bugs just because they involve the interaction with Qt, we're screwed.

@futurist You might experiment with [phantomjs-cef](https://github.com/KDAB/phantomjs-cef) and see if it does what you want.  It's not out of the question that that will be the basis for a 3.0.
