### ISSUE TITLE
'use strict' + duplicate property name triggers confusing error message.

### ISSUE THREAD

**Issue by kmayer** [ariya/phantomjs#14325]
Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

```
± km |master ✗| → phantomjs --version
2.1.1
```

What steps will reproduce the problem?

```
± km |master ✗| → phantomjs 
phantomjs> 'use strict'; var o = {p: 1, p: 2};
Unexpected token '}'

  phantomjs://repl-input:1 in global code
phantomjs> 
```

Which operating system are you using?

OS X Yosemite 10.10.5

```
± km |master ✗| → uname -a
Darwin jake 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
```

Did you use binary PhantomJS or did you compile it from source?

`brew install phantomjs`

Please provide any additional information below.

In strict mode, the error _should be_

> SyntaxError: property name p appears more than once in object literal

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

but also, this is no longer true in ES6 https://bugzilla.mozilla.org/show_bug.cgi?id=1041128

In any case, the syntax error is confusing, and when running Jasmine tests, it doesn't issue the appropriate error at all (it was just dumb luck that we had an old, ancient version of Firefox, v29, lying about that we discovered the root cause).

**Comment by sterpe** [comment]
I just ran into the same thing, and spent way too long, because `PhantomJS` reports it as `SyntaxError: Unexpected token ','` in my  case.

Dr. @ariya even Esprima parser doesn't err on this.  Basically this is a runtime javascript bug in PhantomJS, and needs to be fixed -- mostly because it just takes hours to figure out the issue since it's no longer an error and doesn't have the correct error message.

**Comment by sterpe** [comment]
![screen shot 2016-12-14 at 2 27 49 pm](https://cloud.githubusercontent.com/assets/678398/21203897/923ea116-c209-11e6-871a-3c9c0896b68f.png)
