### ISSUE TITLE
Phantomjs 2.1.1 not showing any error

### ISSUE THREAD

**Issue by rezaxdi** [ariya/phantomjs#14399]
Latest version of phantomjs (2.1.1) doesn't output any error in linux, tested on ubuntu 16.04 & centos 7.

**Comment by Vitallium** [comment]
Could you please elaborate?

**Comment by rezaxdi** [comment]
What exactly do you need to know ? I just changed from phantomjs 1.9.8 to 2.1.1 and know when there is any error happening I just don't see any thing being output to the terminal in Ubuntu 16.04

For example even if there is a syntax error inside the script, I don't see any error printed in output of phantomjs.

**Comment by nonjene** [comment]
In windows also has this problem, most of the time error is not output, the process just freezing there, nothing stdout, I have to slice my code to debug it.

Here is the example, test.js:
```js
'use strict';
const EventEmitter = require('events');
const event = new EventEmitter();
console.log(event.on);
```
```shell
phantomjs test.js
```
nothing out.
Remove 'use strict' will show no 'events' module error.  But I think this is not the main reason because in many case I didn't add strict mode and it still not show error message.

btw, there are another bug: After `npm install events`, above JS without strict mode will echo `TypeError: undefined is not an object (evaluating 'event.on')`. Change `const` to `var` will fixed.

**Comment by Vitallium** [comment]
I think this is related to https://github.com/ariya/phantomjs/issues/12973 The fix is in the master branch, but we didn't release the version with that fix yet.
