### ISSUE TITLE
Outdated docs on crash reporting?

### ISSUE THREAD

**Issue by joshkel** [ariya/phantomjs#14560]
The documentation at http://phantomjs.org/crash-reporting.html appears to be out of date. It talks about obtaining debug symbols from [the downloads page](https://bitbucket.org/ariya/phantomjs/downloads), but current versions don't have debug symbols, and it talks about how to view the crash dump, but no crash dump is generated.

It looks to me like support for crash dumps and debug symbols was removed in #13668 but the documentation was never updated to match.

**Comment by GurpreetSK95** [comment]
Hi! I would like to contribute if you're up for it

**Comment by zackw** [comment]
Last year (!) I wrote a draft of a new guide to troubleshooting and
reporting bugs in PhantomJS, but it never got enough feedback to promote to
official.  Everyone interested in this, please read and kibitz
http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22

**Comment by Judahmeek** [comment]
@zackw Your docs looked good to me. I'd go ahead and implement your draft even if you have to polish it up later, because right now you have docs that don't match the reality of the phantomjs system and that creates developer anxiety (I spent the time required to track this issue down because I wanted to know why my version of phantomjs wasn't created the dump file that the crash reporting docs implied it should be creating.).
