### ISSUE TITLE
How to build master?

### ISSUE THREAD

**Issue by Epskampie** [ariya/phantomjs#14637]
Just a quick heads-up to let you know that building master has become very hard for newcomers due to lack of instructions since [build.py was removed](https://github.com/ariya/phantomjs/commit/70acb2f317b919d65502289082465164a5ef0c08).

I tried the `qmake && make` commands as suggested, but it fails with the following error: `Project ERROR: You must set the environment variable WEB_INSPECTOR_RESOURCES_DIR to generated Web Inspector resources`. I have no idea how to get web inspector resources, googling doesn't help.

**1. Which version of PhantomJS are you using?**
Master branch.

**2. What steps will reproduce the problem?**
  1. Check out master branch
  2. Install dependencies: http://phantomjs.org/build.html
  3. `qmake && make`
  4.  Project ERROR: You must set the environment variable WEB_INSPECTOR_RESOURCES_DIR to generated Web Inspector resources

**3. Which operating system are you using?**
Ubuntu GNOME 16.04

**4. Did you use binary PhantomJS or did you compile it from source?**
Source.

**Comment by Vitallium** [comment]
Yes, there is no step-by-step instruction. I am going to update it this week.

**Comment by Jevin23** [comment]
+1

**Comment by markusschlebusch** [comment]
Is there any draft version of the instructions available? I'll need to build the latest Version on Linux immediately. Also it would be great if the instruction would contain a description how to build with static libraries (ICU, ...). Thanks a lot!

**Comment by Vitallium** [comment]
You can start from building new QtWebKit - https://github.com/annulen/webkit/wiki
This is the most important part.

**Comment by brandon93s** [comment]
Any updates on the step-by-step to building master?

Thanks!

**Comment by markusschlebusch** [comment]
Hi @Vitallium. Thanks for this hint, but the build of QtWebKit failed on my Ubuntu VM. I've opened an issue there: https://github.com/annulen/webkit/issues/355

**Comment by markusschlebusch** [comment]
Hi @Vitallium, build and installation of QtWebKit is done. What's the next step?

**Comment by leeight** [comment]
+1

**Comment by Vitallium** [comment]
@markusschlebusch now just do a regular Qt project build. Keep in mind that if you installed QtWebKit in a different location you also need to set environment variable QMAKEPATH.

**Comment by leeight** [comment]
@Vitallium I already build qtwebkit follow [the wiki](https://github.com/annulen/webkit/wiki), and install to `/usr/local` directory. After that i switch to phantomjs directory and run `qmake && make`, still not work.  Is there some missing steps ?

**Comment by Vitallium** [comment]
@leeight please post the output of `qmake && make`

**Comment by leeight** [comment]
@Vitallium It works now. but after run `bin/phantomjs`, it crashed. I got a similar stacktrace like this issue: <https://bugs.webkit.org/show_bug.cgi?id=158297>

**Comment by markusschlebusch** [comment]
@Vitallium Thanks for update. I've the same issue reported inntially while executing qmake && make: Project ERROR: You must set the environment variable WEB_INSPECTOR_RESOURCES_DIR to generated Web Inspector resources

How can I fix this?

**Comment by Vitallium** [comment]
`WEB_INSPECTOR_RESOURCES_DIR` - this option is required for static build only. Due to how the Qt resource system works you can't build static lib with resources. Resources must be build against the executable file or a shared library. 

If you use static build, you need to set this variable to:
```
export WEB_INSPECTOR_RESOURCES_DIR=YOUR_WEBKIT_BUILD_DIR/BUILD_TYPE/DerivedSources/WebInspectorUI
```
where:

- `YOUR_WEBKIT_BUILD_DIR` - your WebKit build directory. If you didn't use the custom output dir, it will be like this: `WEBKIT_SOURCE/WebKitBuild`
- `BUILD_TYPE` - `Debug` or `Release`

**Comment by markusschlebusch** [comment]
Thanks for this hint. Unfortunately this is the next error with `qmake && make`:
....
config.cpp:37:20: fatal error: QWebPage: No such file or directory
compilation terminated.

QWebPage was installed with the regular QtWebKit installation here: 
`/usr/local/include/QtWebKitWidgets/QWebPage`

**Comment by Vitallium** [comment]
I assume this path is not in the INCLUDE in your Makefile. Can you please paste the line with which you built QtWebKit?

**Comment by markusschlebusch** [comment]
I build QtWebKit with this command:
`WEBKIT_OUTPUTDIR=`pwd`/build/qt Tools/Scripts/build-webkit --qt     --release     --cmakeargs="-DCMAKE_PREFIX_PATH=/home/markus/Qt5.4.1/5.4/gcc_64"`

**Comment by Vitallium** [comment]
Did you set `QMAKEPATH` variable before building PhantomJS?

**Comment by markusschlebusch** [comment]
Yes `export QMAKEPATH=/home/markus/Qt5.4.1/5.4/gcc_64/bin`

**Comment by Vitallium** [comment]
This is wrong. `QMAKEPATH` should point to the new QtWebKit root folder.
 Because when you invoke `qmake` from `/home/markus/Qt5.4.1/5.4/gcc_64/bin` qmake knows about its modules, but it doesn't know anything about new QtWebKit. So you need to point to its mkspec.

You installed QtWebKkit to `/usr/local`, so your QMAKEPATH will be `export QMAKEPATH=/usr/local`
Don't forget to clean the PhantomJS directory before doing the build again :)
See [here](https://github.com/annulen/webkit/wiki/Using-QtWebKit-in-your-project) for more information about using new QtWebKit.

**Comment by markusschlebusch** [comment]
I've set `export QMAKEPATH=/usr/local` and cleared the PhantomJS directory but it's still the same problem. Also the other option to create a `.qmake.conf` didn't change anything.

**Comment by Qantas94Heavy** [comment]
At the moment, the following code in [`src/phantomjs.pro`](https://github.com/ariya/phantomjs/tree/master/src/phantomjs.pro#11) is unconditional (lines 11-14):

    WEB_INSPECTOR_RESOURCES_DIR = $$(WEB_INSPECTOR_RESOURCES_DIR)
    isEmpty(WEB_INSPECTOR_RESOURCES_DIR): {
        error("You must set the environment variable WEB_INSPECTOR_RESOURCES_DIR to generated Web Inspector resources")
    }

I saw that in @Vitallium's fork that this is moved inside the `config(static)` conditional: https://github.com/Vitallium/phantomjs/commit/16450bb919a0f5763651de39abc0ca2966ddae76

This may be why you're still unable to build PhantomJS.

**Comment by Vitallium** [comment]
@Qantas94Heavy exactly. PhantomJS 2.5 can be built with system (shared) Qt. That's why current condition is wrong.

**Comment by markusschlebusch** [comment]
I've invested much time to simply compile a current PhantomJS binary for Linux. Unfortunately I wasn't successful until now. Is there any nightly build or something else where I can get a binary?

**Comment by Qantas94Heavy** [comment]
@markusschlebusch I don't think there is, but I have [managed to compile it on openSUSE](https://build.opensuse.org/package/show/devel:languages:nodejs/phantomjs) -- you need to edit the file that I was referring to earlier.

It seems to requires Qt 5.6 or higher, as well as QtWebkit.

**Comment by Vitallium** [comment]
The minimum required version is 5.5. 5.6 is strongly advised for redirect signal. I decorated them with proper defines, so you can build PJS against 5.5 (or even 5.3 version).

**Comment by mishu-** [comment]
Any news on a way to build phantom.js? The documentation refers to a file that doesn't exist. The `deploy` repo can be successfully nuked because it's obsolete. There is no Makefile anywhere in the repo. 
Any pointers?

**Comment by Qantas94Heavy** [comment]
@mishu- you have to edit the file I was referring to earlier, then run `qmake-qt5` (or just `qmake`, depends on your system), then run `make`.

**Comment by johnspackman** [comment]
@mishu- I've just built using the fork from https://github.com/eisnerd/phantomjs, the standard instructions for building work just fine.

**Comment by wcummings** [comment]
Here is the full process I used to build master on Ubuntu 16.04:

1. Checkout phantom

2. Install new Qt version. I [followed these instructions for Ubuntu](https://wiki.qt.io/Install_Qt_5_on_Ubuntu) and installed Qt5.7 in my home directory

3. Add the new Qt bin directory to your path, its something like `/home/user/Qt5.7.0/5.7/gcc_64/bin`. Verify you're using the right qmake w/ `qmake --version`.

4. [Build new webkit version](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux). I got a [zip file from github](https://github.com/annulen/webkit/archive/qtwebkit-stable.zip), since the repo is huge and takes forever to checkout. Make sure to specify your new Qt directory w/ `-DCMAKE_PREFIX_PATH`.

5. Set QMAKEPATH to /usr/local, run qmake && make in the phantom directory

*Make sure to run `git clean -dxfq` between qmake attempts to purge the old makefile!*
