### ISSUE TITLE
PhantomJS: How to prevent all page redirects??

### ISSUE THREAD

**Issue by leem32** [ariya/phantomjs#14635]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1

3. Which operating system are you using?
windows 7 (Dev) Linux (Prod)

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

I need to be able to take screenshots of webpages before they redirect.

At the moment if I take a screenshot of google.com or yahoo.com for example, it actually takes a screenshot of google.co.uk and uk.yahoo.com.

I found [this script](https://stackoverflow.com/questions/26809256/how-to-configure-poltergeist-or-phantomjs-to-not-follow-redirects#26809652), but it looks like you need to explicitly state the URL's to prevent redirecting to them. This won't work in my case because the URL's are from user input so they could be anything.

```javascript
// My phantomJS script
var system = require("system");

var page;
var myurl = system.args[1];

var renderPage = function(url) {
page = require('webpage').create();

page.open(myurl, function(status) {

    if (status === "success") {
        var pageTitle = myurl.replace(/http.*\/\//g, "").replace("www.", "").split("/")[0];
        var filePath = "img/" + pageTitle + '.jpg';
        window.setTimeout(function () {
        page.render(filePath, { format: 'jpeg', quality: '75' });
        console.log(filePath, '|', myurl);
        phantom.exit(0);
        }, 200);
    } else {
        console.log('|', myurl);
        phantom.exit(1);
    }


 });

};

renderPage(myurl);
```
I notice google chrome has a built in option called Enable phishing and malware protection which Disables Redirecting. Could I access this in phantomJS maybe.

Any help would be greatly appreciated.

Thanks

**Comment by sramzan** [comment]
Have you tried working with some of the Phantom hooks? The one you probably want to work with is 'onResourceReceived()' so that you could mess with the url & redirectUrl. These parameter provided to this callback has both the passed url, and the redirect url.

Resources that may be helpful:
[Phantomjs onResourceReceived api](http://phantomjs.org/api/webpage/handler/on-resource-received.html) 
[Example on someone messing with the redirect](https://gist.github.com/amenzhinsky/5245915)

Hope this helps!
