### ISSUE TITLE
screen capture image are different with website

### ISSUE THREAD

**Issue by jyhyen** [ariya/phantomjs#14686]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. page.render for screen capture
  2. the capture image are different between the result shown on browser

3. Which operating system are you using?
win7 professional SP1

4. Did you use binary PhantomJS or did you compile it from source?
use PhantomJS binary from the download page

5. Please provide any additional information below.
I do a lot test and I find that the image on IE 11.0.34, firefox 50.0.2, chrome 55.0.2883.75 m are the same. But on older firefox and chrome 54.0.xxxx show the same image which is captured by Phantomjs, I think the problem probably cause by webkit with old version.

Browser with latest version show like the first image.
![img](https://cloud.githubusercontent.com/assets/24242528/21005786/289df942-bd71-11e6-9b28-3ade63a3f49c.png)

Browser with older version and Phantomjs screen capture show like the second image.
![img2](https://cloud.githubusercontent.com/assets/24242528/21005795/3850acf4-bd71-11e6-86ee-e356fdddd4b2.png)

**Comment by CyborTronik** [comment]
Experiencing similar issue.
Writing automation test so checking the placeholder with CSS and got result confirmed that as exists(if I do change it, the tests fails). but when I do render the page I see no placeholder and even the label on input button. Maybe because placeholder text and labels are inserted onPageLoad. Whatever is a issue while even the PhantomJS detects them right, but doesn't render them.
PhantomJS 2.1.1
