### ISSUE TITLE
PhantomJS 2.1.1 not delegating click events from table row to table cell

### ISSUE THREAD

**Issue by yanekk** [ariya/phantomjs#14724]
PhantomJS 2.1.1, Windows 10, binary downloaded from website. Initialized with following built-in webdriver with --webdriver switch on port 8090.

1. Prepare simple HTML page:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test Page</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script>
        $(function() {
            $('#clickme td').click(function() {
                $("body").append($("<h1>").text("Success"));
            });
        });
    </script>
  </head>
  <body>
    <table>
      <tr id='clickme'>
        <td>Test1</td>
        <td>Test2</td>
      </tr>
    </table>
  </body>
</html>
```
2. Pay attention to event binding - click event is attached to each table cell, not table row.
3. Prepare sample script:
```csharp
var driver = new RemoteWebDriver(new Uri("http://localhost:8090"), new DesiredCapabilities());
driver.Navigate().GoToUrl(@"file:///C://<path-to-you>/test.html");

driver.FindElementById("clickme").Click();
Assert.AreEqual("Success", driver.FindElementByTagName("h1").Text); // will fail, because h1 is not created

driver.FindElementByCssSelector("#clickme td").Click();
Assert.AreEqual("Success", driver.FindElementByTagName("h1").Text); // will pass
```
4. Generally, first try finds table row via id selector element and clicks it, failing with no header being created, even though it should be through event delegation (as it works in ChromeDriver, or Chrome in general). Second try attaches to table cell, therefore event is fired directly on bound element and h1 element is created and visible.

**Comment by twalpole** [comment]
I'm confused by why you think this should work? Events propagate up the DOM structure not down it so an event fired on the row is never going to be seen on the cells

**Comment by yanekk** [comment]
As I mentioned above, the same code works on ChromeDriver, FirefoxDriver and naturally by clicking on the row by hand. I assume, that it is obvious that PhantomJS should work the same way as other drivers.

**Comment by twalpole** [comment]
The reason the other drivers "work" (and manually) is that they ARE actually clicking one of the &lt;td> elements, not because of event propagation (events propagate up the DOM not down).  You can see this by adjusting the CSS of your example to create spacing between the two td elements and then running it again.  This is happening because the two tds completely overlap the tr in your example.  There's an argument that can be made saying that PhantomJS should just click the point on the screen that would be the middle of the tr (which is what is happening with the other drivers), or that it should warn that it can't actually click the element you're asking it to, and an even bigger argument that if you want it to click the td element you should just click the td.

**Comment by yanekk** [comment]
I agree with you completely about event propagation - thanks for sorting it out. I raised this issue not because of pure curiosity and bug-hunting, but because of real life situation. In my application under test, click event is attached to each table cell, but not to table row. Previously, tests were running smoothly because of usage of ChromeDriver and clicking row was ultimately clicking cell that overlaps it. That works perfectly fine and with all benefits that headless browsers provides, I started with experiments leading to replace ChromeDriver by PhantomJS. After switching to PhantomJS, all of my tests started to fail because of different click handling between drivers. As you said - we may discuss if PhantomJS should handle element clicking identically to other popular drivers (requiring testers to make adjustments to their tests) or do proper way. Either way, my honest opinion is that drivers shouldn't work differently, at least in terms of event-handling.

**Comment by jesg** [comment]
@yanekk  @twalpole unfortunately calculating the proper coordinates for `WebPage::sendEvent` is non-trivial.  the easiest way to calculate the coordinates is with `element.getBoundingClientRect`. `element.getBoundingClientRect` is relative to the current frame so you need to recursively propagate up nested frames to get the absolute coordinates.  after which ghostdriver would need to validate that the element is clickable at the derived coordinates.

**Comment by jesg** [comment]
see https://github.com/jesg/ghostdriver/tree/jesg-sendevent-click for a prototype of how this would be done.

**Comment by twalpole** [comment]
I'm still confused as to why when the user needs to click on a &lt;td> element you would write a test that attempts to click on the &lt;tr>?  

At the very least the title of this issue should be changed to something like "PhantomJS doesn't click on overlapping child elements when instructed to click on their parent" so that it correctly identifies what you're claiming is an issue.  However I think this issue should probably actually be closed because PhantomJS doesn't provide a "click" behavior so any "issue" here is either in ghostdriver or the driver you're using, one of which is probably generating fake click events and directing them straight to the element you're instructing it to rather than sending a "real" click event at a location on the page.

**Comment by twalpole** [comment]
@jesg Yep, and then to it would need to calculate the elements intractability - https://www.w3.org/TR/webdriver/#element-interactability - to be webdriver compliant

**Comment by jesg** [comment]
@twalpole you are right this use case should fail in selenium with an error message saying another element would receive the click event.

> I'm still confused as to why when the user needs to click on a <td> element you would write a test that attempts to click on the <tr>?

that is an anti-pattern.  something must be slightly off with chromedriver.  according the the chromedriver [isElementClickable](https://github.com/SeleniumHQ/selenium/blob/master/javascript/chrome-driver/atoms.js#L214) atom it should return an error when clicking on a descendant.

i was planning on using chromedriver's `isElementClickable` atom or [isInteractable](https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/dom.js#L84) atom to determine if i can click on the element.

**Comment by twalpole** [comment]
@jesg Actually the code you linked to actually specifically allows the click if the click location turns out to be a descendant of the element that was to be clicked - https://github.com/SeleniumHQ/selenium/blob/master/javascript/chrome-driver/atoms.js#L251 - with a warning message.  I think that's not technically webdriver compliant, but the webdriver spec is rapidly changing at the moment.
