### ISSUE TITLE
New release date or nightly builds

### ISSUE THREAD

**Issue by Paxa** [ariya/phantomjs#14728]
There are several bug fixes and ES6 features support already in master, I would love to use it

When new release is expected? Or is there any nightly builds from master?

**Comment by lunij** [comment]
Good point! We have January again, so would be nice to see a new release coming. Release 2.1.1 is from January 2016, (almost) one year ago.

**Comment by Vitallium** [comment]
Hi! You are right. We want to decrease the gap between releases in 2017. Right now I have nightly binaries for Windows. The main problem is that there is no a full static build for Linux (I really don't have time on this). Before dropping the 2.5 release I need to finish one thing - macOS.

**Comment by jesg** [comment]
@Vitallium the dependencies you listed in issue #14458 look fine to me.  just need to document the correct packages to install for different linux distributions.  the previous release had some system dependencies as well (fontconfig, and glib).

**Comment by orangecms** [comment]
@Vitallium I can build just fine on Linux with Qt 5.7 if I remove the line https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L369 - it is awesome, only 2.5MB in size. However, when I run the tests, 3 pass, 7 fail, 2 fail as expected, 168 had errors. I guess that is because of the context issue. If I keep the line, I get an error saying that QWebSettings does not have a member WebSecurityEnabled. Please let me know if I can help somehow, I'm really looking forward to the next release. :)

**Comment by orangecms** [comment]
Also tested with 5.6.2, same thing.

**Comment by johnspackman** [comment]
@Vitallium A new release would be very helpful - I've just lost the best part of a week trying to solve problems where loading randomly does not complete on Linux; this was solved by the latest master, but I use Centos 6 on the server so your Ubuntu/shared library builds don't work.  I've had to recompile from source, except there are no instructions for building from source and now that build.py has been removed this was a major headache - even after figuring out how to compile it, I also need to recompile git from source, install C++11 compiler, etc).  

Thanks to the work of @eisnerd and his https://github.com/eisnerd/phantomjs fork I now have a working phantomjs (the first time since 1.9.8, which regrettably I had to upgrade from).  

The code in master seems to be a huge improvement in stability, and given the number of people who were experiencing show-stopper problems IMHO this makes a new release very important.  Many people have switched away from phantomjs (including OSS projects like nightmare) exactly because of unreliability - and like them we started evaluating other products this week.  If we were not under such huge pressure to release I would have abandoned it also.

**Comment by Vitallium** [comment]
@johnspackman Hi.

>A new release would be very helpful - I've just lost the best part of a week trying to solve problems where loading randomly does not complete on Linux

We will do releases more often now (since 2.5).

>I've had to recompile from source, except there are no instructions for building from source and now that build.py has been removed this was a major headache - even after figuring out how to compile it, I also need to recompile git from source, install C++11 compiler, etc).

Unfortunately, we will drop old systems because we need GCC 5 at least to build WebKit with cool features like FTL JIT. If you have a chance to install GCC 5 from backports, it's good to you.

>Thanks to the work of @eisnerd and his https://github.com/eisnerd/phantomjs fork I now have a working phantomjs (the first time since 1.9.8, which regrettably I had to upgrade from).

Keep in mind that we don't support 1.X and 2.1 anymore.

>Many people have switched away from phantomjs (including OSS projects like nightmare) exactly because of unreliability - and like them we started evaluating other products this week. If we were not under such huge pressure to release I would have abandoned it also.

I understand you. But this a real story when a huge project doesn't have many developers.

Thanks!

**Comment by johnspackman** [comment]
@Vitallium Hi

> We will do releases more often now (since 2.5).

Great news!  Thank you, I realise that there are fundamental changes to the build system underway.

> Unfortunately, we will drop old systems because we need GCC 5 at least to build WebKit 

But a static library build would be fine - it's only an issue with shared libraries which makes your Ubuntu build unsuitable.  Centos6 is still supported long term, although I could fairly easily upgrade to Centos 7 ... however, AIUI your Ubunutu build would still not work because there are different and/or conflicting shared libraries.

> If you have a chance to install GCC 5 from backports, it's good to you.

Not ideal but not out of the question - eisnerd's fork produces a build with dependencies on shared libraries, and I can use the RedHat devtools-2 backport to compile on Centos6 and then have a working binary for my platform. 

**But the real issue** was that you'd removed the build.py script before any kind of replacement was ready, including any instructions on how to go about it.  This means that master is *not buildable* unless you are already deep in Qt development.  @ariya 's comment about this on another issue was to "consult a Qt expert", which is not helpful (and probably not the whole story either).

> Keep in mind that we don't support 1.X and 2.1 anymore.

All my problems were with 2.1.1; ironically, 1.9.8 was reliable but because of other bugs I had to upgrade to 2.1.1 - which was fine on my development machine (OSX) but on Centos 6 and 7 would fail to reliably load pages.  I saw on the issue that this appeared to have been solved (thanks in no small measure to your efforts) so decided to switch to self compile.

> I understand you. But this a real story when a huge project doesn't have many developers.

I completely understand, I am a long time user of OSS and a core dev on a large OSS project myself and very well aware of how much it costs to commit time and effort to an unfunded project.  Kudos is great but doesn't buy tea or beer :)  My complaint is that the reliability issues should take/have taken higher priority (despite core devs having a "it works on my machine" experience) because of the number of users reporting the problem, and that removing the ability to build master significantly degrades the ability of anyone other than the core devs to try and solve or work around their problems.  

But anyway - the current master looks great and although we havn't done much testing yet it looks like we'll be putting it into production "real soon now".  Thanks for everybody's efforts in making this happen!

**Comment by ariya** [comment]
> But this a real story when a huge project doesn't have many developers.

And I already wrote a little bit about this, see #14541. The reality is, the demand and the help do not grow in lock steps (guess which one is slower).

**Comment by ckxion** [comment]
I would appreciate some clarification on latest version (or stable version for Linux)

This page [http://phantomjs.org/releases.html](http://phantomjs.org/releases.html) shows latest version as 2.1
The download page shows 2.1.1
Statements above suggest no support for 2,1 - does that include 2.1.1?
Statements above suggest that 2.5 for Linux is not yet available - is it?

**Comment by ckxion** [comment]
Still keen to get a reply on this

**Comment by Vitallium** [comment]
@ckxion it's available here https://bitbucket.org/ariya/phantomjs/downloads 

We announced it (2.5 beta) in our mailing list. When we will ready to ship 2.5 version, all links will be updated.

**Comment by dogancelik** [comment]
Is there a reason why builds are not released here but on Bitbucket?

Bitbucket Downloads page is not advanced as Github's. It's a one big folder for downloads where on Github you can uploads builds for each tag or commit.

**Comment by ariya** [comment]
@dogancelik See for #13953 for details. Short version: we'll likely have a new CDN-based download place.

**Comment by dogancelik** [comment]
@ariya You may not need a CDN because Github counts downloads.

Example: https://api.github.com/repos/Medium/phantomjs/releases/2489362

![count](https://cloud.githubusercontent.com/assets/486818/22634111/8c3d1c3e-ec2f-11e6-884e-15c1acaa5a6e.png)

**Comment by ariya** [comment]
@dogancelik Please add useful information to #13953 so this issue can be focused on 2.5 specific.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
