### ISSUE TITLE
How to stop Phantom.js from outputting weird debug data to the HTML pages?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [ariya/phantomjs#14749]
I often get weird debug stuff such as: 'piwik.js:5 in b
The method setSiteId is registered more than once in "paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'

This is printed as part of the actual HTML page when captured with Phantom.js, but never shown in real browsers. *Not even in the console*! So why is Phantom.js outputting this on my pages, and how do I turn this behaviour off? I've looked through all the command line options and find nothing mentioning this (surprise, surprise).

**Comment by zackw** [comment]
I've had this happen myself.  These are console messages.  To intercept all of them, you must define handlers for _all_ of the console-related page callbacks, and you must also define a `page.onPageCreated` that sets the handlers for newly created sub-pages.  See https://github.com/zackw/tbbscraper/blob/master/collector/scripts/pj-trace-redir.js for a complete worked example.

You probably aren't seeing these in real browsers because real browsers have pop-up blockers and PhantomJS doesn't.

(This is not an actionable bug report and I'm going to close it.  I implore you to post questions like these to the mailing list, the forum, or Stack Overflow.)

**Comment by ddfssdfkofdsfighdfuigf** [comment]
I don't know if you see this, but did you actually link to the right file? I can't tell what the (huge) script is doing or what part(s) you mean I should copy and paste to make this error go away. Can you clarify this?

Also, why is this done to begin with? That is, why would console data ever be printed as HTML data on the actual web page? Makes no sense whatsoever.

**Comment by zackw** [comment]
@ddfssdfkofdsfighdfuigf  Yes, I linked to the right file.  You will not be able to "copy and paste to make this error go away"; that's why I called it a _worked example_ of the technique for solving the problem, not an immediate solution.  Start reading at `p_onPageCreated`.

> why is this done to begin with?

Because you are writing the webpage to stdout, and the default console handler also writes to stdout, and console handlers don't inherit when child windows are created.  If you want us to take this as a a bug report along the lines of "the default console handler should write to stderr" or "console handlers should inherit", I wouldn't disagree with either assertion, but we might be unable to make either change for fear of breaking other people's existing scripts.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
I guess you are talking about this line?
page.onConsoleMessage = p_onConsoleMessage.bind(page);

I don't understand why you can't just say what I need to type to make it stop outputting console messages to the standard output. This default is ridiculous. Not in my wildest dreams would I ever consider defaulting to this, and not even have a simple option to change it. Please help.

**Comment by zackw** [comment]
This is a _bug tracker_, not a support forum. It would be inappropriate for me to discuss this any further with you here.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
E-mail lists are horrible, and I don't even have an e-mail address I can use. Everyone wants to be paid for e-mail accounts these days. And Stack Exchange/Overflow never see/respond to anything I ask.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
And the manual lies: "By default, console messages from the web page are not displayed. Using this callback is a typical way to redirect it."

**Comment by zackw** [comment]
If you post an MCVE on Stack Overflow, or on http://discuss.phantomjs.org/ , and then post a link to that here, I will respond there.  You're right that the manual is incorrect.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
I tried making an account on that last link, but they never sent me an e-mail to the disposable e-mail. Often happens. I don't have the energy to deal with account creations everywhere.

**Comment by zackw** [comment]
If you are avoiding the big free webmail providers for privacy reasons, you might consider [riseup.net](https://riseup.net/).  But if you just don't like to use email, well, I'm sorry, but we _do_ like email (as do nearly all free-software developers) and there's a limit to the amount of time we are willing to spend accommodating people who don't.  This goes double for misuse of the bug tracker.  Every issue filed that isn't a clear, actionable bug report or feature request makes it harder to do release management.  If you keep filing cries for help in the bug tracker we may have to block you.

Anyway, I wrote up the problem I think you are having, here: http://discuss.phantomjs.org/t/console-messages-from-the-webpage-arent-discarded-by-default/49 It includes a shorter chunk of example code.  You will probably still need to modify it somewhat, but I hope it demonstrates more obviously what you need to do.  If I haven't correctly read your mind, please tell me about it _there_.  Not here.
