### ISSUE TITLE
Provision to skip or ignore JavaScript error (on page third-party JS)

### ISSUE THREAD

**Issue by jagkaran** [ariya/phantomjs#14897]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**2.1.1**
2. What steps will reproduce the problem?
  Consider the code below:
```
var steps = [];
var testindex = 0;
var testError = 0;
var loadInProgress = false; 
var webPage = require('webpage');
var page = webPage.create();
page.settings.userAgent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36';
page.settings.javascriptEnabled = true;
page.settings.loadImages = false; 
phantom.cookiesEnabled = true;
phantom.javascriptEnabled = true;

steps = [

    //Step 1 - Open  site
    function() {
		
        console.log('Step 1 - Open UK site');
        page.open("http://www.example.com/", function(status) {
            if (status !== 'success') {
                console.log("Adidas UK is loading for long");
            }
		
        });

    },
function() {
        console.log('Step 2 - Search for the product');
        page.evaluate(function(login, password) {
            bla bla bla ...
        });

    },	
function() {
        bla bla ...

    },	
many more functions ...

//Execute steps one by one
interval = setInterval(executeRequestsStepByStep, 50);

function executeRequestsStepByStep() {
    if (loadInProgress == false && typeof steps[testindex] == "function") {
        //console.log("step " + (testindex + 1));
        steps[testindex]();
        testindex++;
    }
    if (typeof steps[testindex] != "function") {
        console.log("Script is completed...");
        phantom.exit();
    }
}

page.onError = function(msg, trace) {
			
    var msgStack = ['ERROR: ' + msg];

    if (trace && trace.length) {
        msgStack.push('TRACE:');
        trace.forEach(function(t) {
            msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function+'")' : ''));
        });
    }
    console.error(msgStack.join('\n'));
	phantom.exit(2); //this is needed in case any error related to phantom script occurs.

};

```

3. Which operating system are you using?
**Windows 7 32 bit**

5. Please provide any additional information below.
In the above code example, when i execute the script i get something like this in Step 1 and Step 5:
```
ERROR: TypeError: undefined is not a constructor (evaluating 'sf_chat_Widget.loc
ale.includes("CH")')
TRACE:
 -> https://e-com.secure.force.com/adidasContact/servlet/servlet.FileDownload?fi
le=01520000003gdry: 58 (in function "loadWidget")
 -> http://www.adidas.co.uk/: 3367 (in function "onload")

  phantomjs://code/UkScript.js:158 in onError
```
and i wish to ignore or skip this error without halting the execution of steps in script and only catch such errors caused by phantom JS script which is not happening and throwing all errors occurred on page.

> Is there already a way to skip or ignore specific on page error and just catch errors happened in phantom js script?

**Comment by seansd** [comment]
you don't need to add phantom.exit for page.onError.  page.onError is just signaling to you that the page itself had a JS error (which may have been caused by your own evaluation of code in the page for your tests).  

you can't really "ignore specific" errors b/c whenever a page error is thrown to that handler you only get the message, line, number, and file which are almost always not useful.

you shouldn't drive your tests by checking if there are JS errors in the page unless you are absolutely 100% certain that you own all the code in that page.

**Comment by jagkaran** [comment]
Hi @seansd 

Thanks for your valuable inputs on this but my intention was to catch only those errors occurred during the execution of the script which i wrote, for an instance:
- Some DOM element was not found
- Syntax errors
- Syntactical errors etc.

But under the scope of page.onerror() all errors (on page and script related) are getting caught with some additional information and i know to eliminate this scenario i can use try catch on steps[] but again page.onerror() seems to be a best practice to include in the script.

May be you can suggest something with other examples to eliminate on page errors and catch all script related error.

P.S. I'm new to phantomjs if you find something illogical please don't hesitate to fire. :)

Your help would be much appreciated!

Thanks

**Comment by seansd** [comment]
It's not possible to catch syntax errors. . . 

page.onError is effectively the same as adding a top level window.onerror handler in the DOM, and it's basically a last resort to report an error that was uncaught (as well as silencing them to the user)

You can't really use that call back for what your suggesting. . . 

What you can do is write a phantomJS script that checks for the existence of a known set of DOM elements, and so you'd write various tests to do that. . . rather than trying to use phantomJS to discover a problem later
