### ISSUE TITLE
svg conversion to png incorrect

### ISSUE THREAD

**Issue by christophemacabiau** [ariya/phantomjs#14919]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. rasterize test.svg: phantomjs rasterize.js test.svg test.png '400px*400px'
  2. compare test.svg and test.png

3. Which operating system are you using?
fedora 23

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.

I have reported a bug to webkit, but they think it's a phantomjs bug... 
https://bugs.webkit.org/show_bug.cgi?id=170052

Can someone help me identifying the bug origin?
Can you confirm that the code responsible of the png conversion is:
https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L1101
Am I wrong ?
I don't see nothing in this code that would cause this bug. Something in qt ? or webkit ?

I need some strong arguments to repoen the webkit bug...

**Comment by trejkaz** [comment]
I have found at least two problems converting SVG to PNG using phantomjs which are not occurring when I view the same SVG in Chrome:

1. transform doesn't work on some elements. All text elements seem to ignore it, but I even have some <g> in my image which are not having scaling applied.

2. Line thickness is not being obeyed whatsoever. There are very thin gridlines in my image, which get rasterised to very thick, black lines. I thought maybe it was only when rasterising to PNG, but I also see the problem when rasterising to PDF, so it isn't just because it's converting to pixels and not changing the opacity appropriately.

My source image is publicly available:

https://github.com/trejkaz/keyboard/blob/master/custom-keycaps.svg
