### ISSUE TITLE
render the image different from chrome

### ISSUE THREAD

**Issue by wulin76** [ariya/phantomjs#14965]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1.run the js script, as bellow
```
var page = require('webpage').create();
var fs = require("fs");
var args = require('system').args;
```

`page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.94 Safari/537.36';`

```
page.open('http://w.qq.com', function(status){
    if (status == 'success') {
        setTimeout( function() {
        page.render('index.png'); 
        console.log(page.content);
    },12000);
    }
});
```

  2.
  3.

3. Which operating system are you using?
WINDOW 10

4. Did you use binary PhantomJS or did you compile it from source?
use binary PhantomJS

5. Please provide any additional information below.

**Comment by itsusony** [comment]
I don't think this is an issue.
Image rendering in Firefox, Opera, Safari are different from chrome, too.

**Comment by kensoh** [comment]
Seconding @itsusony. PhantomJS is based on WebKit, it is like a cousin of Chrome and Safari but a lot of developments have been made since then in each browser's individual direction to be considered a near 100% similarity in behaviour.

@wulin76 if you really really want a real browser consider using Selenium to drive Chrome or others, and maybe combine with Xvfb to make headless. Also, Chrome headless is coming, everyone is just waiting to see through which tool or new tool it gets introduced into web automation world.
