### ISSUE TITLE
Long Tıme Working with Phantom

### ISSUE THREAD

**Issue by Selimerkan** [ariya/phantomjs#14972]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1
2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
Windows 7
4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
I wrote c# code.Logining a website then Im getting data in this website. I am refreshing page in two minutes. 
Everything are ok in start
After 17-18 hours later Im looking there arw no error but it was stopped after refreshing

**Comment by kensoh** [comment]
Hi @Selimerkan if you change the script such that it refreshes every 2 minutes but quits after 1 hour, then use crontab to call the script to run once every hour does it work for you?

I do not think PhantomJS is designed to be long running for so long. For batch automation I normally invoke new PhantomJS instance (through CasperJS) for each iteration, so that whatever garbage in memory can be cleared and it can start fresh for execution stability.
