### ISSUE TITLE
PDF randomly do not display some images on large file

### ISSUE THREAD

**Issue by ebhoren** [ariya/phantomjs#15040]
I'm trying to generate PDF from an HTML page with a lots of pages and images. When generating a PDF from a very long HTML page, some images do not show even if they display correctly on the HTML source. This bug hit random images all around the PDF.

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. **2.1.1**
2. What steps will reproduce the problem?
    1. Generate PDF from HTML page with lots of pages and images (10+ pages and 40+ images)
    2. The PDF do not display some images, even if they exist on the server and everything is fine in HTML version. Problems start at page 7.
5. Which operating system are you using? **Linux (64 bits)**
6. Did you use binary PhantomJS or did you compile it from source? **binary PhantomJS**
7. Please provide any additional information below. 
The PDF result: http://innotexprotection.com/en/catalogs/rapid-delivery-gear/?download=yes 
HTML source: http://innotexprotection.com/en/catalogs/rapid-delivery-gear/?printable=yes

Here is my code to generate PDF:
**rasterize.js**
```
"use strict";
var page = require('webpage').create(),
    system = require('system'),
    address, output, size;

if (system.args.length !== 3) {
    console.log('Usage: rasterize.js URL filename');
    phantom.exit(1);
} else {
    address = system.args[1];
    output  = system.args[2];

    page.viewportSize   = { width: 600, height: 600 };
    page.paperSize      = { format: 'pdf', orientation: 'portrait', margin: '1cm' };
    page.zoomFactor     = 1.0;
    page.settings.resourceTimeout = 90000;
    page.settings.webSecurityEnabled = false;

    page.onError = function(){ console.log('PhantomJS OnError: ' + output); phantom.exit(); };
    page.open(address, function (status) {
        if (status !== 'success') {
            console.log('PhantomJS unable to load ' + address);
            phantom.exit();
        } else {
            window.setTimeout(function () {
                //page.dpi = 72;
                page.render(output);
                phantom.exit();
            }, 2000);
        }
    });
}
```

**phantomjs config**
```
{
  "ignoreSslErrors": true,
  "outputEncoding": "utf8",
  "webSecurityEnabled": false,
  "javascriptEnabled": true
}
```

Any ideas on how to solve this?
Thanks a lot

**Comment by wwhgtt** [comment]
same problem width you , have you solved it ? my page also have lots of images and PhantomJs do not provide a listener for like window.onload or document.ready

**Comment by ebhoren** [comment]
@wwhgtt No. Didn't find any solution and nobody from the community replied to this request. I will post my solution here if i find something.

**Comment by wwhgtt** [comment]
@ebhoren  i find an API    from phantomJS :onLoadFinished   i  try to do some tests ,it will happen when window.onload, but not every time correct, still testing

**Comment by ebhoren** [comment]
@wwhgtt i've tried onLoadFinished, and from my tests, the event is triggered 2 times when running PhantomJS from OSX, and never on Linux system. Have you similar problem?

**Comment by wwhgtt** [comment]
@ebhoren  yes , unluckily，our  system is Linux

**Comment by ebhoren** [comment]
@fdanielsen Any thoughts on this issue? 
@wwhgtt Have you tried something else to resolve your problem?

**Comment by fdanielsen** [comment]
@ebhoren Well, in our issue it turned out to be a SSL certificate issue. phantomjs did not consider the certificate of some images loaded through SSL to be valid. The solution to this was to update the root certificates in the Docker container. We do not use `ignoreSslErrors` however, so not sure if that would circumvent the issue.

**Comment by ebhoren** [comment]
@fdanielsen It turn out i'm not loading any images or assets from a SSL domain. Also, i'm not using Docker at all. Any ideas?

**Comment by fdanielsen** [comment]
@ebhoren Not particularly, no. The test page mentioned in the original issue doesn't exist anymore, but I do see on another page that you use JS to only display images after they're within the visible viewport. Could this be a reason?

Also, in general about load events we've previously successfully evaluated JS in the page to call back out to the phantom JS renderer notifying when things are ready. I'd assume you could do the same to hook into the native `onload` event in the browser context rather than go through phantomjs events like `onLoadFinished`. Very crude, untested example:

```javascript
page.onInitialized = function () {
    page.evaluate(function () {
        window.addEventListener('load', function() {
            window.callPhantom();
        });
    });
};

page.onCallback = function () {
    // Do your stuff here
    phantom.exit();
};
```

**Comment by ebhoren** [comment]
@fdanielsen Sorry, that did not work too. It seem to work even worse than previously.

**Comment by fdanielsen** [comment]
@ebhoren Sorry it didn't help. Sadly we haven't experienced this particular issue ourselves, as mentioned the issue this was cross-referenced in turned out to be a problem with SSL certificates. Did you investigate the other issue with lazy loading images on scroll as I mentioned?

Otherwise, since we're not experiencing this issue, and I'm not an expert in phantomjs internals, there's not much else I can do to help. If you think it's a problem with onload event reporting, maybe try adding a delay before you generate the PDF and see if that ends up displaying more images in the result. Or, random thought, if this in some way has to do with memory usage when rendering many images (are the images large in filesize?).

We are currently using phantomjs in many different situations, even generating multi-page PDF reports rendering SVG graphs, and haven't come across this issue yet.

Finally, as a last resort, maybe you're case isn't solvable in phantomjs currently. If so, it could be worth looking into the recent headless rendering support in Chrome.

**Comment by engharb** [comment]
I have a problem in phantomjs with rendering a large HTML file i.e 15MB to pdf. PhantomJS log file shows that is succeeded but the pdf files were not generated.

it works well with small HTML file i.e 3MB.

My OP: MAC OSX

Any suggestions.

Regards,
