### ISSUE TITLE
Fost show as Italic

### ISSUE THREAD

**Issue by chesiri** [ariya/phantomjs#15052]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.use webshot
  2. render mi html
  3. capture a image

3. Which operating system are you using?
windows 10
4. Did you use binary PhantomJS or did you compile it from source?
source
5. Please provide any additional information below.
I am using webshot based on phantomjs and when I convert my page into image the embedded font appears as italic, I already checked all the styles and I put 'font-style: normal! Important;' To all texts.

I'm using the Montserrat-SemiBold.ttf font
And probe with Montserrat-SemiBold.otf. This last one looks less Italic

any ideas?

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by Vitallium** [comment]
@kensoh I suggest you to stop doing that. Because it looks like spam. Thanks!

**Comment by kensoh** [comment]
Hi Vitaly @Vitallium thanks for your reply! I've just removed all the posts I made except for the one above. I'm very sorry, I had the impression that the project is [no longer supported from this](https://github.com/ariya/phantomjs/issues/14946#issuecomment-303985078).

And wanted to retain resources within PhantomJS/CasperJS-like ecosystem. It looks like my understanding is wrong, but that is ok, because it will be good news for many people!

**Comment by Vitallium** [comment]
@kensoh you can use this mailing list for announcements - https://groups.google.com/group/phantomjs 
We try to keep our issue tracker for issues only. Thank you ;-)

**Comment by kensoh** [comment]
Thanks for your tip! I see.. I also don't have anything to do now, because looks like there is some new development going on with PhantomJS (and the new commits) ;) I've been using PhantomJS (indirectly through CasperJS) for 2 years, and glad to finally get a chance to speak to its maintainer :smile:
