### ISSUE TITLE
Unable to click on a button - Using Selenium click() function.

### ISSUE THREAD

**Issue by NiteeshChennoju** [ariya/phantomjs#15084]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
     PhantomJSDriver  jar- 1.4.0
     phantomjs-2.1.1-EXE
2. What steps will reproduce the problem?
  1.Open parent form, Click on image icon of particular field.
  2. The image will open an inline/platform window(but not OS window).
  3. Switching to an inline window frame, then **click on button**.(which it wont click, even after if i use javascript executor, Actions class) But it will work for Firefox browser, chrome browser, IE browser.

3. Which operating system are you using?
Windows 7 Professional
4. Did you use binary PhantomJS or did you compile it from source?
 i included phantomJSdriver jar into my framework.
5. Please provide any additional information below.
   The scenario mentioned will work for IE browser,Chrome browser, and Firefox.
  selenium version  - 3.4.

**Comment by twalpole** [comment]
You don't provide the actual error that you get when attempting to click the button but take a screenshot of the page and look at what you think you're trying to click on -- you'll probably find that it is either not on the page, or is overlapped by something else.  This is likely because you're app is using CSS or JS features that are not supported by PhantomJS 2.1
