### ISSUE TITLE
Dockerhub image for phantomjs

### ISSUE THREAD

**Issue by vaibhavsood** [ariya/phantomjs#15161]
Hi,

Want to check if there is a docker image/Dockerfile for phantomjs which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official phantomjs image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by ariya** [comment]
Since the Linux binary is nearly self-container and dependency-free, it's an overkill to create a dedicated Docker image for that. It is very easy to add one line that does `wget` or `curl` the binary and extract it, ready to be use, to any standard `Dockerfile`.

Feel free to share some tricks on using PhantomJS with Docker and we'll be sure to share it with other PhantomJS users.

We will close this for now. Let's reopen it if we revisit the subject in the near future.
