### ISSUE TITLE
In Selenium 3.8.1 PhantomJS marked as deprecated webdriver

### ISSUE THREAD

**Issue by manlix** [ariya/phantomjs#15314]
Hi,

I am very sorry that writing to issues instead another place (please moved to right place or close the issue).

I like PhantomJS and used it with Selenium as webdriver but since Selenium 3.8.1 [PhantomJS is deprecated](https://github.com/SeleniumHQ/selenium/commit/c5e4a585f1e3c4b3468ec93ab50d3668d47aef1b#diff-16fa7e439f764ef9668676a211769d37R8) and recommend us to use either Chrome or Firefox in headless mode.

Is it OK? What do you think about it? Thanks.

**Comment by pixiuPL** [comment]
@manlix Ive talked about this with Selenium's devs, but they are rather uncooperative, so there is not much I can do about this. Sorry

**Comment by ylavoie** [comment]
Many users felt abandoned when sad news started flowing about phantomJS stopping and may have pushed for that. If releases star flowing again, it may help Selenium reconsider.

**Comment by pixiuPL** [comment]
@ylavoie yes. Let them direct all their anger at Selenium. Not PJS. Because PJS relies on Selenium heavily....

**Comment by ariya** [comment]
Due to the development being suspended until further notice (#15344), it is unlikely that we have the time to ensure and verify that the latest Selenium will work correctly with PhantomJS. Thus, the characterization is correct.

When the development is resumed again in the future, we will revisit the issue.
