### ISSUE TITLE
Thanks a lot for your return into the project

### ISSUE THREAD

**Issue by oebspm** [ariya/phantomjs#15400]
Dear Ariya,

Please publish info how to donate you and not to loose your involvement into the project.

Regads!

**Comment by ariya** [comment]
Hi @oebspm, please check #13861. Thanks!

**Comment by diegocr** [comment]
First of all, sorry for hijacking this closed ticket, but i am also very excited to see development continues and didn't wanted to open another such similar one.

This is just awesome, is there any chance we can have a page with _"Nightly builds"_ from the CI jobs for example? it'll be great as basic es6 support is becoming kinda essential nowadays (not asking to update the npm package because i assume this might be under some beta/alpha status atm :))

Sincerely, keep up the good work!
